### ISSUE TITLE
How to get title in french language by IMDB_ID?

### ISSUE THREAD

**Issue by afzaalahmad969** [tboothman/imdbphp#105]
Hello all, Please provide me php code to get titles of all movies in french language.. I am waiting for an answer.

**Comment by jreklund** [comment]
It's in the readme: [Configure languages](https://github.com/tboothman/imdbphp#configure-languages)

**Comment by afzaalahmad969** [comment]
I did but it doesn't giving me in french..?

**Comment by jreklund** [comment]
Then you will need to provide some context.
What movie did you try it with?
In what country are your server located?
How do your code look like?

**Comment by afzaalahmad969** [comment]
pirrates of carribean 2k17

**Comment by afzaalahmad969** [comment]
<?php
require "vendor/autoload.php";
$config = new \Imdb\Config();
$config->language = 'fr-DE,fr,en';
$imdb = new \Imdb\Title('1790809', $config);
echo $imdb->title(); // Lost in Translation - Zwischen den Welten
?>

**Comment by afzaalahmad969** [comment]
require "vendor/autoload.php";
$config = new \Imdb\Config();
$config->language = 'fr-DE,fr,en';
$imdb = new \Imdb\Title('1790809', $config);
echo $imdb->title(); // Lost in Translation - Zwischen den Welten

**Comment by jreklund** [comment]
You got the wrong territory code. At the moment you got Germany.
$config->language = '**fr-FR**,fr,en';
