### ISSUE TITLE
View person in cache

### ISSUE THREAD

**Issue by Alexisback** [tboothman/imdbphp#109]
View person in cache

is this possible?
![view person in cache](https://user-images.githubusercontent.com/18039740/32838207-391a571c-ca21-11e7-8e28-7338e511f5e4.png)

Thank

**Comment by jreklund** [comment]
I have sent in a pull request adding Person inside the "Cache Contents" function.

**Comment by Alexisback** [comment]
Thank you

**Comment by tboothman** [comment]
This is released now
