### ISSUE TITLE
last update and re-download the card

### ISSUE THREAD

**Issue by Alexisback** [tboothman/imdbphp#116]
I set the cache to "0", so I do not have to re-download the cards
this is useful but ..

you can insert these features

1) show last update (year, day, month and time)
2) re-download the card (via a button or script)

![features](https://user-images.githubusercontent.com/18039740/36412088-b63f29bc-1629-11e8-934e-7e2068d2fe02.png)

Thanks for you works

**Comment by jreklund** [comment]
Personally I don't deem these functions necessary in a demo application. It's ment to give you a hint on what type of information you can get from IMDb (every function aren't being used thought) and not serve as a real application for storing information. There are specialized applications for movie collections. 

If I remember correctly we don't store the date (last update) on the saved file anywhere. `cache_expire` only get's checked in a while loop and delete the old files. So you need to modify the cache library to store the actual date of the file too.
