### ISSUE TITLE
Open file limit

### ISSUE THREAD

**Issue by BurakBoz** [tboothman/imdbphp#118]
```
PHP Warning: gzopen(): gzopen failed in vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line 74
PHP Warning: gzputs() expects parameter 1 to be resource, boolean given in vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line 75
PHP Warning: gzclose() expects parameter 1 to be resource, boolean given in vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line 76
PHP Warning: gzopen(vendor/imdbphp/imdbphp/src/Imdb/../../cache//title.tt1799585): failed to open stream: Too many open files in vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line 74
PHP Warning: gzputs() expects parameter 1 to be resource, boolean given in vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line 75 
PHP Warning: gzclose() expects parameter 1 to be resource, boolean given in vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line 76 
PHP Warning: dir(vendor/imdbphp/imdbphp/src/Imdb/../../cache/): failed to open dir: Too many open files in vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line 95 
PHP Fatal error: Call to a member function read() on boolean in vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line 97
```

I think we have a missing fclose some where in Cache.php

**Comment by jreklund** [comment]
Are this error message from the demo application or your own code?
Can you run the script if you download the zip file instead of installing it from composer?
Can you run a previous version? (5.2.5) Cache interfaced changed in 6.0.
What PHP version do you have?

**Comment by tboothman** [comment]
@jreklund That's <6.0 because there isn't `dir() ... src/Imdb/Cache.php on line 95` in 6.0. Also it's composered in because of the vendor/imdbphp/imdbphp directory structure.

I can see one bug but it'd be useful to know if you're creating lots of Imdb classes in one PHP execution or you have a ton of cache files (or maybe both) to try and narrow this down a bit

**Comment by jreklund** [comment]
@tboothman My bad. The function matched up perfectly except the last two lines with 6.0. I recommended running it without composer (vendor) because it looks like a folder permission error.

**Comment by tboothman** [comment]
Gotcha, completely misread your zip sentence.
I'm going to redo this insane code to do with converting to gzip as I don't think it works and it's 10+ years old and pretty unreadable and it looks like it's just double reading the file for no particular reason in almost every circumstance

**Comment by tboothman** [comment]
Give dev-master a go @BurakBoz and see if that's helped

**Comment by jreklund** [comment]
Just a note regarding ad248ada02f6e789dffc1de52f2cc3597466ec29. Don't forget to change `converttozip` in the sample config file, if it's going to be the new default value.

PS. Missed the whole `Too many open files in` of course it's not a folder permission thing. But the first error messages can be. DS

**Comment by BurakBoz** [comment]
Sorry for late response I use "imdbphp/imdbphp": "^5.1" and php 5.6 cli
I completed my database upgrade in 5 or 7 times interrupted but I will upgrade to latest version as soon as possible and inform you all
This is how I get this error I have more than 3K movie in my db (it was a temporary solution to upgrade my db so code quality is not so good ignore that please):
```
set_time_limit(3600 * 8);
    use \Imdb\Config as imdbConfig;
    use Imdb\Exception;
    use Imdb\Title;
    use \Imdb\TitleSearch as imdbTitleSearch;
    use \Naz\Lib\UpDownModel;
    class imdbDataUpdate
    {
        private $db = null, $imdbConfig = null;
        public function __construct()
        {
            /* DataBase */
            $this->db = new UpDownModel(MOVIE_DB);
            if (!$this->db->connect()) throw new \Exception("Database connection error!");
            /* imdb configuration */
            $this->imdbConfig = new imdbConfig();
            $this->imdbConfig->language = 'tr-TR';
            $this->imdbConfig->cachedir = cache . 'imdb/';
            if (!file_exists($this->imdbConfig->cachedir)) @mkdir($this->imdbConfig->cachedir, 0755, true);
            while (true)
            {
                if($this->db->countEmptyYears()>0)
                {
                    $this->db->__temp_imdbdata(function ($data){
                        $changes = $data;
                        try
                        {
                            $imdb = new Title($data["imdb"]);
                            $changes["myear"] = $imdb->year();
                            $changes["mrating"] = $imdb->rating();
                            echo $changes["imdb"]." ".$changes["myear"]." ".$changes["mrating"]."\n";
                        } catch (\Exception $e) {}
                        return $changes;
                    });
                }
                else
                {
                    echo "Tamamlandı!";
                    break;
                }
            }

        }

    }
    try
    {
        new imdbDataUpdate();
    } catch (\Exception $e) {}
```

**Comment by tboothman** [comment]
Give dev-master a go, I think it will have fixed the problem
