### ISSUE TITLE
endyear incorrect on series

### ISSUE THREAD

**Issue by paxter** [tboothman/imdbphp#119]
For example Sneaky Pete.

`$title = new \Imdb\Title(5011816);
echo $title->year();
echo $title->endyear();`

Output:
`20152015`

Both return 2015, which is incorrect. endyear() should not be 2015 because the series has not ended yet. Same goes for yearspan():
`Array ( [start] => 2015 [end] => 2015 ) `

**Comment by jreklund** [comment]
There are actually some tv-shows that spans over only one year like [Cupid](http://www.imdb.com/title/tt1143289/). So that code got written for those cases. I have now modified it in case a tv-show haven't finished yet.

**Comment by paxter** [comment]
Wow, thanks a lot for your fast fix! It's working great now. And thank you for your awesome imdb api! :)
