### ISSUE TITLE
Connection with IMDB

### ISSUE THREAD

**Issue by greenhouseffecto** [tboothman/imdbphp#122]
Hi, when i try to search a film from my database (php4dvd) this fatal error appears to me.
Can you please help me?

Thank you

```
Fatal error: Uncaught exception 'Imdb\Exception\Http' with message 'Failed fetch url [https://www.imdb.com/find?s=tt&q=la+dolce+vita] Received HTTP code 403 from proxy after CONNECT' in /php4dvd-master/lib/imdbphp/src/Imdb/Request.php:84
Stack trace:
#0 /php4dvd-master/lib/imdbphp/src/Imdb/Pages.php(72): Imdb\Request->sendRequest()
#1 /php4dvd-master/lib/imdbphp/src/Imdb/Pages.php(54): Imdb\Pages->requestPage('https://www.imd...')
#2 /php4dvd-master/lib/imdbphp/src/Imdb/MdbBase.php(136): Imdb\Pages->get('https://www.imd...')
#3 /php4dvd-master/lib/imdbphp/src/Imdb/TitleSearch.php(28): Imdb\MdbBase->getPage('la dolce vita')
#4 /php4dvd-master/includes/movie.update.inc.php(41): Imdb\TitleSearch->search('la dolce vita', Array)
#5 /php4dvd-master/index.php(135): require_once('/membri/skynexs...')
#6 {main} thrown in /php4dvd-master/lib/imdbphp/src/Imdb/Request.php on line 84
```

**Comment by jreklund** [comment]
Hi, have you done any changed to your configuration file?
/config/config.php
/config/config.default.php
/lib/imdbphp/conf/php4dvd.ini

Are you using the latest version? As it's says master I would think so; I haven't made a new release just for the updated imdbphp I included in it a few days ago.

If you haven't; please test the /demo/ application in this project, as it's not included in php4dvd.

As far as php4dvd goes, It works fine from my dev machine and hosting provider with moviesearch for `la dolce vita`. But I don't cache error messages, my bad. :-)

**Comment by tboothman** [comment]
Something to do with using https through a http proxy maybe? Not entirely sure. Have you updated something recently? New config?

**Comment by greenhouseffecto** [comment]
With your files for change from http to https something is changed. But now i have this error:

Fatal error: Class 'BrowserEmulator' not found in /membri/skynexsrl/php4dvd-master/lib/imdbphp/src/Imdb/Request.php on line 20

How can i fix this problem?

**Comment by jreklund** [comment]
You can download php4dvd version 3.8.0. It dosen't contain the https fixes for IMDb, but you can instead get the 302 Found redirection problem fixed in 6.0.1 instead.
So I would try to fix your webhost settings instead (try different php version).

BrowserEmulator haven't been used since version 5.0.0 of imdbphp released on Oct 16, 2016. What version did you actually grab? php4dvd first public version (3.1.1) uses 5.0.1 so you didn't grab it from [jreklund/php4dvd](https://github.com/jreklund/php4dvd).

**Comment by greenhouseffecto** [comment]
i think that the version is 3.8.0 but i send you the file so you can check if is correct.
[php4dvd-master.zip](https://github.com/tboothman/imdbphp/files/1961584/php4dvd-master.zip)
I put this file in altervista, i follow the configuration, but every time a problem occurs.

**Comment by greenhouseffecto** [comment]
Fatal error: Uncaught exception 'Imdb\Exception\Http' with message 'Failed to retrieve url [http://www.imdb.com/find?s=tt&q=s]. Status code [403]' in /membri/skynexsrl/php4dvd-3.8.0/lib/imdbphp/src/Imdb/Pages.php:88 Stack trace: #0 /membri/skynexsrl/php4dvd-3.8.0/lib/imdbphp/src/Imdb/Pages.php(53): Imdb\Pages->requestPage('http://www.imdb...') #1 /membri/skynexsrl/php4dvd-3.8.0/lib/imdbphp/src/Imdb/MdbBase.php(137): Imdb\Pages->get('http://www.imdb...') #2 /membri/skynexsrl/php4dvd-3.8.0/lib/imdbphp/src/Imdb/TitleSearch.php(28): Imdb\MdbBase->getPage('s') #3 /membri/skynexsrl/php4dvd-3.8.0/includes/movie.update.inc.php(41): Imdb\TitleSearch->search('s', Array) #4 /membri/skynexsrl/php4dvd-3.8.0/index.php(135): require_once('/membri/skynexs...') #5 {main} thrown in /membri/skynexsrl/php4dvd-3.8.0/lib/imdbphp/src/Imdb/Pages.php on line 88

I repeated the procedure from the beginning without changing anything, now the error that appears is this.
P.S I used your zipped file (3.8.0 version)

**Comment by greenhouseffecto** [comment]
Thank you very much, jreklund
I am gonna write to my hosting provider to see if IMDb is actually blocked or just miss-configured.

Meanwhile I activated the debug mode and I am posting below the more detailed exception
`Fatal error: Uncaught exception 'Imdb\Exception\Http' with message 'Failed fetch url [https://www.imdb.com/find?s=tt&q=s] Received HTTP code 403 from proxy after CONNECT' in /membri/skynex/php4dvd-master/lib/imdbphp/src/Imdb/Request.php:75 Stack trace: #0 /membri/skynex/php4dvd-master/lib/imdbphp/src/Imdb/Pages.php(72): Imdb\Request->sendRequest() #1 /membri/skynex/php4dvd-master/lib/imdbphp/src/Imdb/Pages.php(54): Imdb\Pages->requestPage('https://www.imd...') #2 /membri/skynex/php4dvd-master/lib/imdbphp/src/Imdb/MdbBase.php(136): Imdb\Pages->get('https://www.imd...') #3 /membri/skynex/php4dvd-master/lib/imdbphp/src/Imdb/TitleSearch.php(28): Imdb\MdbBase->getPage('s') #4 /membri/skynex/php4dvd-master/includes/movie.update.inc.php(41): Imdb\TitleSearch->search('s', Array) #5 /membri/skynex/php4dvd-master/index.php(135): require_once('/membri/skynex/...') #6 {main} thrown in /membri/skynex/php4dvd-master/lib/imdbphp/src/Imdb/Request.php on line 75`
