### ISSUE TITLE
[Question] Get series ID from episode ID

### ISSUE THREAD

**Issue by paxter** [tboothman/imdbphp#124]
Sorry for using an issue for a question. :/

Is it possible to get the series IMDb-ID by an episode IMDb-ID? I didn't found something related to this in the source code. That would be very helpful for me.
For example. I've that https://www.imdb.com/title/tt3216414/ and I want this: https://www.imdb.com/title/tt3749900/

Thanks in advance.

**Comment by jreklund** [comment]
You can find that information in get_episode_details();
```
Array ( [imdbid] => 3749900 [seriestitle] => Gotham [episodetitle] => Pilot [season] => 1 [episode] => 1 [airdate] => 2014-09-22 )
```

**Comment by paxter** [comment]
Ah, that's awesome!
Thanks a lot man. ;)
