### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by paxter** [tboothman/imdbphp#125]
The exception "Failed to retrieve url" of the requestPage() function in pages.php is thrown, but nowhere caught.

``` 
if (200 == $req->getStatus()) {
        return $req->getResponseBody();
    } elseif ($redirectUrl = $req->getRedirect()) {
        $this->logger->debug("[Page] Following redirect from [$url] to [$redirectUrl]");
        return $this->requestPage($redirectUrl);
    } else {
        $this->logger->error("[Page] Failed to retrieve url [{url}]. Response headers:{headers}", array('url' => $url, 'headers' => $req->getLastResponseHeaders()));
        if ($this->config->throwHttpExceptions) {
          $exception = new Exception\Http("Failed to retrieve url [$url]. Status code [{$req->getStatus()}]");
          $exception->HTTPStatusCode = $req->getStatus();
          throw $exception;
        } else {
          return '';
        }
    }
```

I'm not very familiar with exceptions in php, but it looks like, that has to be caught in the imdbphp project and not outside.

Reproducing this issue is very easy. Just call an imdb-id which does not exist.
`$this->imdbObj = new \Imdb\Title(2364345);`

**Comment by paxter** [comment]
Also disabling the "throwHttpExceptions = 1" option, results into an empty output instead of display any error message.

**Comment by paxter** [comment]
Thanks for your reply. I already tried to put the new `new \Imdb\Title(2364345);` into a try/catch block and that does not work. That's why I'm opened this issue.

**Comment by tboothman** [comment]
`new \Imdb\Title(2364345);` doesn't actually make any requests, it will only fail when you try to request something from imdb e.g. 
```
$title = new \Imdb\Title(123456);
$title->title(); // The exception will be thrown here, and in any other method call on $title
```

**Comment by paxter** [comment]
Ah sorry, you are right. There are some lines in my code without a try/catch block. Sorry for disturbing you.
