### ISSUE TITLE
method plot_split returns undesired tekst

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#127]
this movie has no plot listed:
https://www.imdb.com/title/tt1395080/

but plot_split returns this:

`It looks like we don't have any Plot Summaries for this title yet. Be the first to contribute! Just click the "Edit page" button at the bottom of the page or learn more in the Plot Summary submission guide.~Plot Summary submission guide~https://contribute.imdb.com/updates/guide/plot?ref_=ttpl_emt`

Can this been removed in imdbphp?

**Comment by jreklund** [comment]
It should now work as expected. Have a go at it.

**Comment by duck7000** [comment]
@jreklund 

Thanks it is working as it should now!
And thanks for the quick reply!
