### ISSUE TITLE
Invalid person ID

### ISSUE THREAD

**Issue by GeorgeFive** [tboothman/imdbphp#130]
Not sure if this is an IMDb issue or a code issue, but it's weird.

Demo: tt7424200

The site looks fine, but when you pull data for it, you'll see this for just one of the cast members:

[9] => Array ( [imdb] => Kal-El Cage [name] => Kal-El Cage

It's filling in his name instead of IMDb ID.  Comparison, the every other item is fine...

[10] => Array ( [imdb] => 0000115 [name] => Nicolas Cage

The only oddity that I can see is that it's the first eight-digit ID that I've come across... not sure if that's relevant or a coincidence.

**Comment by tboothman** [comment]
Ah that's a good one. They've finally got over 10 million 'people', i bet the regex is for nm\d{7}
