### ISSUE TITLE
runtime() does not work for series

### ISSUE THREAD

**Issue by paxter** [tboothman/imdbphp#135]
Example code:
```
$title = new \Imdb\Title(5011816); 
echo $title->runtime(); 
print_r($title->runtimes());
```
Both are empty.

**Comment by jreklund** [comment]
Hopefully this is it this time. I had seen some pages with an empty runtime on the title page. But those at least had the json. But now we are checking for json, title and technical page.

**Comment by paxter** [comment]
Looks fine now. Thanks for fixing @jreklund. :)
