### ISSUE TITLE
runtime() don't work

### ISSUE THREAD

**Issue by Machou** [tboothman/imdbphp#136]
Hello

The function "`public function runtime()`" don't work for this movie https://www.imdb.com/title/tt3960240/

Work for this : https://www.imdb.com/title/tt5942214/

**Comment by jreklund** [comment]
It works just fine using the fallback method. Make sure to download the latest master release.

**Comment by tboothman** [comment]
To be fair people probably shouldn't be using master so that's understandable. I'll do a release with the latest fixes a little later
