### ISSUE TITLE
Slashes in role

### ISSUE THREAD

**Issue by GeorgeFive** [tboothman/imdbphp#14]
Good job fixing #12 - much appreciated.

However, this does introduce one new bug (or it was a recent bug that I missed).  Some roles have slashes in them to separate multiple characters that an actor played in that movie, but any role that has a slash in it gets truncated.

Example, see: http://www.imdb.com/title/tt0462538/fullcredits

role = Marge Simpson / Selma / Patty
gets truncated to
role = Marge Simpson /

**Comment by tboothman** [comment]
Sorry about that, I thought about that case when I was writing the tests but forgot to actually write it :P

**Comment by IzzySoft** [comment]
*LOL* OK, SH (shit happens). I'll take care for the packages when I'm back home (just saw you've tagged 2.4.1) – so please don't wonder that the demo/packages on the server are not yet updated :hushed:
