### ISSUE TITLE
Localize imdbphp (genres, country, etc.)

### ISSUE THREAD

**Issue by Machou** [tboothman/imdbphp#140]
Hi,

I've been using your script for some time now, and I've created my own custom locales for countries, genres and many others locales needed to translate.

for example, I use this function for countries (it is not complete, but a good part is present)

```
function imdb_Country_EnToFr($country)
{
	return ['Argentina' => 'Argentine', 'Armenia' => 'Arménie', 'Australia' => 'Australie', 'Australasia' => 'Australasie', 'Belarus' => 'Biélorussie', 'Belgium' => 'Belgique', 'Brazil' => 'Brésil', 'Bulgaria' => 'Bulgarie', 'China' => 'Chine', 'Denmark' => 'Danemark', 'Estonia' => 'Estonie', 'Finland' => 'Finlande', 'Germany' => 'Allemagne', 'Greece' => 'Grèce', 'Hungary' => 'Hongrie', 'Iceland' => 'Islande', 'India' => 'Inde', 'Indonesia' => 'Indonésie', 'Ireland' => 'Irlande', 'Israel' => 'Israël', 'Italy' => 'Italie', 'Japan' => 'Japon', 'Kuwait' => 'Koweït', 'Lithuania' => 'Lituanie', 'Malaysia' => 'Malaisie', 'Mexico' => 'Mexique', 'Netherlands' => 'Pays-Bas', 'Norway' => 'Norvège', 'Peru' => 'Pérou', 'Poland' => 'Pologne', 'Portugal' => 'Portugal', 'Russia' => 'Russie', 'Singapore' => 'Singapour', 'South Africa' => 'Afrique du Sud', 'South Korea' => 'Corée du Sud', 'Spain' => 'Espagne', 'Sweden' => 'Suède', 'Switzerland' => 'Suisse', 'Taiwan' => 'Taïwan', 'Thailand' => 'Thaïlande', 'UK' => 'Angleterre', 'United Arab Emirates' => 'Émirats arabes unis', 'USA' => 'Américain', 'West Germany' => 'Allemagne'];
}
```

Maybe, it's possible to add a locale for this script ? and use the locale in `new \Imdb\Config();` ?

**Comment by paxter** [comment]
I like that idea.

**Comment by jreklund** [comment]
That would mean that we need 100+ arrays to convert to every possible language. Personally I recommend that you utilize already available lists like https://github.com/umpirsky/country-list. And keep this as is, just a scraper.

**Comment by tboothman** [comment]
In an ideal world the library would return the purest and most clear form for all these things (ISO codes etc) but as jreklund said it's not really this library's job to do translations - it just returns raw data.
