### ISSUE TITLE
IMDB title not working.

### ISSUE THREAD

**Issue by alr2413** [tboothman/imdbphp#144]
Hi,
It seems that IMDB title attribute is not working anymore!
Please fix it.
Thanks.

**Comment by tboothman** [comment]
Looks fine to me. Tests pass.
If you're not on v6.0.4 or master there's no guarantee anything will work - this library follows site changes on imdb.
If you're up to date then I'll need much more information from you:
Which title doesn't work? (all of them?)
What does 'not working' mean? Do any other methods work?

**Comment by alr2413** [comment]
Sorry I made a mistake.
As you mentioned I checked everything and found out that by replacing "orig_title" with "title" attribute my problem has been solved.
Thanks for your quick response.
:)
