### ISSUE TITLE
Akas not working anymore

### ISSUE THREAD

**Issue by vlahde** [tboothman/imdbphp#150]
Just noticed that as from yesterday alsoknow() function return empty array. have installed the latest version using composer require.

**Comment by brunoSmagalhaes** [comment]
I have the same problem.

**Comment by brunoSmagalhaes** [comment]
To fix this just replace in Title.php
$ak_s = strpos($page, "<a id=\"akas\"");
with
$ak_s = strpos($page, 'id="akas"');
