### ISSUE TITLE
[Feature Request] Cinema airdates

### ISSUE THREAD

**Issue by paxter** [tboothman/imdbphp#156]
https://www.imdb.com/calendar/?region=de
https://www.imdb.com/calendar?region=RU
https://www.imdb.com/calendar?region=IT
https://www.imdb.com/calendar?region=US
...

I think, that would be a great feature, to call a function which print dates with upcoming cinema imdb ids.

**Comment by Machou** [comment]
https://www.imdb.com/calendar/?region=fr Too =)

**Comment by Thomasdouscha** [comment]
Yea it would be a great!

**Comment by duck7000** [comment]
I don't think that someone is working on this but i will give it a try

So you want the dates and the imdbid's that would be released at that date?
Title's too?
And should there be some kind of country switch, so you can set the country you want?

**Comment by duck7000** [comment]
PR is created so try it out.
If there are problems or things missing report back here or in PR request

**Comment by duck7000** [comment]
@paxter 
If this works for you could you close this issue?

Less clutter in the issues list is better i think, and this is already approved and merged.

**Comment by paxter** [comment]
Just checked and looks fine. Thanks for implementing @duck7000!

**Comment by duck7000** [comment]
Your welcome, glad to contribute to this library
