### ISSUE TITLE
release date don't work on this movie

### ISSUE THREAD

**Issue by Machou** [tboothman/imdbphp#160]
#### Description
When i parse this movie : https://www.imdb.com/title/tt2034176/

I don't get the release date : **28 September 2018 (UK)**

#### Type
- [X] Bug
- [ ] Question
- [ ] Feature request

**Comment by tboothman** [comment]
Which method? What do you get? Does it work for other films?

**Comment by Machou** [comment]
I use standard method like :

```
<?php
require 'class.imdb-api.php';
$title = new \Imdb\Title(2034176);
```

I get nothing. The var_dump : https://pastebin.com/rkgPS90y

Yes work with others movies.

**Comment by jreklund** [comment]
Dumping `\Imdb\Title` won't get you anything good. It's always "empty". What method are returning incorrect information?

**Comment by Machou** [comment]
Another movie don't work : https://www.imdb.com/title/tt0781511/

**Comment by paxter** [comment]
Both movies are working fine for me. It's a problem on your side. Maybe old imdbphp version or IMDb is blocking your requests for some reason.

**Comment by Machou** [comment]
I have try with fresh version on 2 differents servers :/

**Comment by duck7000** [comment]
> Dumping \Imdb\Title won't get you anything good. It's always "empty". What method/function are returning incorrect information?

i think that you still have to answer this question first before anyone can even try to help
