### ISSUE TITLE
Only purge cache files generated by the library

### ISSUE THREAD

**Issue by kinoute** [tboothman/imdbphp#161]
#### Description

At the moment, the `purge()` function that gets rid of the oldest cache files seems to delete every file in the folder, no matter what kind of cache files it is.

#### Type
- [X] Feature request

#### Expected Results / What do you want to do?

It would be great if the cache purge could only occur on files generated by the library itself like the `title.*.fullcredits` files. When you have a unique cache folder that serves different purposes, you may have different purge time depending of the library that generates these cache files.

#### Actual Results / What is happening?

At the moment, all files older than the setting we set with `cache_expire` get deleted no matter if it comes from other librairies or not.

**Comment by tboothman** [comment]
The cache files are fairly arbitrarily named, I would suggest you put your cache files for this library in its own folder

**Comment by tboothman** [comment]
I could prefix the files with a consistent word, but that would just be a poor mans folder IMO

**Comment by kinoute** [comment]
I understand that using its own folder will be easier but I think we can improve that like, for example, using `glob` in the `purge()` function to get only the lists of cache files generated by imdbphp.

In one of your other files, you do something like this:

https://github.com/tboothman/imdbphp/blob/5069cc16761772976eecb68467ccb94e33511fed/demo/cache.php#L23

I guess it summarizes all the types of cache files generated by the library? If we add this to the `purge()` function, we could only then purge these files with these prefixes.

I could try a PR if you want but my PHP knowledge is not that great.

**Comment by tboothman** [comment]
As I said the cache files aren't particularly consistent. I could probably enumerate them all if I read all the code, but that seems prone to error.
After running the tests the folder contains this:
```
chart
find.q=Forest+Whitaker&s=nm
find.s=tt&q=Cowboy+Bebop
find.s=tt&q=Cowboy+Funk
find.s=tt&q=Doom
find.s=tt&q=Hatfields+.26+McCoys
find.s=tt&q=Home+2015
find.s=tt&q=The+Lord+of+the+Rings.3A+The+Fellowship+of+the+Ring
name.nm0005132.bio
name.nm0386944.publicity
name.nm0594503
name.nm0594503.bio
name.nm0594503.publicity
name.nm0662730.bio
search.title.title_type=tv_episode&sort=moviemeter.2Casc
search.title.title_type=tv_episode&year=2003&sort=num_votes.2Cdesc
search.title.year=2000&languages=en&sort=moviemeter.2Casc
title.tt0056592.alternateversions
title.tt0078788
title.tt0087544
title.tt0087544.fullcredits
title.tt0087544.releaseinfo
title.tt0103074
title.tt0107290.locations
title.tt0107290.releaseinfo
title.tt0108052
title.tt0120737.parentalguide
title.tt0133093
title.tt0133093.alternateversions
title.tt0133093.awards
title.tt0133093.companycredits
title.tt0133093.crazycredits
title.tt0133093.externalreviews
title.tt0133093.externalsites
title.tt0133093.fullcredits
title.tt0133093.keywords
title.tt0133093.locations
title.tt0133093.movieconnections
title.tt0133093.parentalguide
title.tt0133093.quotes
title.tt0133093.soundtrack
title.tt0133093.trivia
title.tt0133093.trivia.tab=gf
title.tt0133096
title.tt0149937
title.tt0149937.fullcredits
title.tt0149937.videogallery.content_type-trailer
title.tt0284717
title.tt0306414
title.tt0306414.awards
title.tt0306414.companycredits
title.tt0306414.episodes
title.tt0306414.episodes.season=1
title.tt0306414.episodes.season=2
title.tt0306414.episodes.season=3
title.tt0306414.episodes.season=4
title.tt0306414.episodes.season=5
title.tt0306414.fullcredits
title.tt0306414.quotes
title.tt0306414.taglines
title.tt0314979
title.tt0338187
title.tt0416449.fullcredits
title.tt0450385
title.tt0579539
title.tt1027544
title.tt1027544.episodes
title.tt1027544.episodes.season=1
title.tt1027544.episodes.season=-1
title.tt1027544.episodes.season=2
title.tt1027544.episodes.season=3
title.tt1286039
title.tt1286039.fullcredits
title.tt1570728
title.tt1570728.technical
title.tt1799527
title.tt2015381.fullcredits
title.tt2039393.plotsummary
title.tt2395427.videogallery.content_type-trailer
title.tt2768262
title.tt3110958
title.tt5011816
title.tt5258960
title.tt7587362
title.tt7618100
title.tt7618100.soundtrack
```

[Symfony's file cache](https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Cache/Traits/FilesystemTrait.php)  works in exactly the same way as this file cache, by purging the entire folder of older files.

Without a third opinion I can't tell if I'm just being stubborn and reluctant to change anything but your request seems to add complexity to something that's consistent with other implementations and if you can just change your config to solve your problem that seems like the best solution

**Comment by tboothman** [comment]
The cache could work work without a purge though, and simply delete expired files as it tried to read them. I don't know how many people would prefer that though. I'm not sure I would

**Comment by kinoute** [comment]
I like the idea of deleting/generating new cache files as being read but I guess that would need a lot of work so...

I guess I will try to find a workaround. Thanks!

**Comment by tboothman** [comment]
If you don't like the cache you can just replace it with anything that implements PSR-16 (simple cache) https://github.com/tboothman/imdbphp#replacing-the-default-cache-disk-cache
