### ISSUE TITLE
metacritic link for movie page

### ISSUE THREAD

**Issue by Thomasdouscha** [tboothman/imdbphp#165]
hello,

I wanna know that is possible to get metacritic url link for movies?
this is not issue. Just i need this and is there anyway to get it or is this option will be add to?

thanks

**Comment by tboothman** [comment]
Not at the moment.
As far as I can see the only link to metacritic is on the [Critic reviews page](https://www.imdb.com/title/tt0133093/criticreviews).

You can add a method to find the link if you want, probably shouldn't be more complicated than a regex for https://www.metacritic.com/movie/[^"\?]+ on that page

**Comment by duck7000** [comment]
@Thomasdouscha 
It's been over 2 years, still interested in this method?
If so what specific link(s)are you after? In the link above from tboothman there are two links:
austinchronicle.com
see all 35 reviews on metacritic.com
I think you want, like tboothman suggest, the see all?

**Comment by Thomasdouscha** [comment]
@duck7000 
I am interested of just metascore value of metacritic. Actually imdb site for many movies show it. But some others not. That'why i opened  that issue how can i get it. Nowadays I am getting directly it from metacritic site. So i am not still interested it.

**Comment by duck7000** [comment]
I don't understand, there already is a method to get, if available, metacritic value?

Or do you mean all ratings from different reviewers like washington post or austin chronicles?

But your not interested anymore so this issue can be closed i guess?

**Comment by Thomasdouscha** [comment]
Yes it can be closed

**Comment by duck7000** [comment]
would you be so kind to close it, i can't
