### ISSUE TITLE
Episode Title not parsed well

### ISSUE THREAD

**Issue by aminerol** [tboothman/imdbphp#166]
#### Description

Some Episodes does not return the title correct but it returns the whole html code

#### Movies / TV-Shows / Person

name: Grey's Anatomy 
episode id = tt9729144

#### Type

Bug 

#### Code
```php
// Avoid posting hundreds of lines of source code.
// Edit to just the relevant portions.
```

#### Expected Results / What do you want to do?

it should return "What I Did For Love  "

#### Actual Results / What is happening?

returned :
```html
What I Did For Love" itemprop="url"> <div data-const="tt9729144" class="hover-over-image zero-z-index no-ep-poster">
<a href="/registration/signin?u=https%3A//www.imdb.com/title/tt0413573/episodes/_ajax%3Fseason%3D15"
onclick="imdb.contribution.clickHandler(event)" class="add-image" > <span class="add-image-container episode-list" style="width:224px;height:126px">
<span class="add-image-icon episode-list" />
<span class="add-image-text episode-list">Add Image</span>
</span>
</a> <div>S15, Ep23</div>
</div>
</a>  </div>
  <div class="info" itemprop="episodes" itemscope itemtype="http://schema.org/TVEpisode">
    <meta itemprop="episodeNumber" content="23"/>
    <div class="airdate">
            2 May 2019
    </div>
    <strong><a href="/title/tt9729144/?ref_=ttep_ep23"
title="What I Did For Love"
```

**Comment by tboothman** [comment]
Which method? episodeTitle or title?

**Comment by tboothman** [comment]
I've never used this library for episodes and there's no test for what is meant to happen with title .. but episodeTitle() would seem the logical method to use to get the episode title, and that will do what you want

**Comment by tboothman** [comment]
Sure you're not using an old version of the library? episodeTitle was changed in https://github.com/tboothman/imdbphp/releases/tag/v6.0.3

**Comment by aminerol** [comment]
no am getting the episodes of a tv show using function episodes() and it return an array with episodes of that tv show

```php
$imdbid =  Input::get('imdbid');
$title = new \Imdb\Title($imdbid);
$seasons = $title->episodes();
foreach ($seasons as $season){
     foreach ($season as $episode){
          echo $episode['title'];
     }
}
```

**Comment by tboothman** [comment]
I can't replicate your problem.
```
Array
(
    [imdbid] => 9729144
    [title] => What I Did For Love
    [airdate] => 2 May 2019
    [plot] =>
    [season] => 15
    [episode] => 23
)
```

**Comment by tboothman** [comment]
I wonder if it's a difference in how the regex works in <7. I don't have php<7 any more and the tests don't run against it either ....

Try changing line 1865 to `. '.+?\shref="/title/tt(?<imdbid>\d{7,8})/.+?"\s+title="(?<title>[^"]+?)"\s+itemprop="name"'` .. that's the change I made before I realised this isn't even a problem for me.

**Comment by aminerol** [comment]
after change that line it works perfect now

**Comment by tboothman** [comment]
What version of php are you using?

**Comment by aminerol** [comment]
am using php 7.2.11

**Comment by brunoSmagalhaes** [comment]
I have the same problem, I'am using PHP Version: 7.0.33-0+deb9u1

**Comment by tboothman** [comment]
I really don't like changing the code without knowing why it's made any difference ... but the current tests still pass and they include episodes without a plot so I guess this is fine.
I'll release this tomorrow
