### ISSUE TITLE
New Amsterdam serie

### ISSUE THREAD

**Issue by brunoSmagalhaes** [tboothman/imdbphp#167]
In the New Amsterdam only lists 17 episodes instead of 22
I'm using PHP Version: 7.0.33-0+deb9u1
My code:

$imdbid="7817340";
$config = new \Imdb\Config();
$config->language = 'en-US,en';
$movie = new \Imdb\Title($imdbid, $config);
$seasons = $movie->episodes();
print_r($seasons);

**Comment by brunoSmagalhaes** [comment]
I think this problem is caused because episodes> 17 have 8 digits

**Comment by brunoSmagalhaes** [comment]
To fix this I have changed the following:

**Find:**
public function episodes()

**edit line:**
. '.+?\shref="/title/tt(?<imdbid>\d{7})/.+?"\s+title="(?<title>.+?)"\s+itemprop="name"'

to
. '.+?\shref="/title/tt(?<imdbid>\d{7,8})/.+?"\s+title="(?<title>.+?)"\s+itemprop="name"'

**Comment by tboothman** [comment]
This has been fixed already, but not released, sorry. #163
