### ISSUE TITLE
8 digit id in directors

### ISSUE THREAD

**Issue by GeorgeFive** [tboothman/imdbphp#168]
I saw some other posts about it, but this still seems to be in place.  If a director has an eight digit id, we're only pulling the last seven digits.

Example, David John on this page:
https://www.imdb.com/title/tt8020970/

Edit - also affects producers.

**Comment by GeorgeFive** [comment]
https://www.imdb.com/name/nm10556058/

Another example.

**Comment by tboothman** [comment]
Yea you're right, the way it parses the ids is different to everything else. I don't think the regex for the number was greedy enough so it was just taking the smallest amount of digits. I'll look to release this tomorrow once i've had change to test it
