### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by darkalchemy** [tboothman/imdbphp#176]
Just a simple request. IMDb has been using 8 digit ids. Could you please change the regex used from ```\d{7}``` to ```\d{7,8}```. It is already this in a few places. I have seen these 8 digit ids for persons and tv, there are likely others.

Thank you

**Comment by jreklund** [comment]
Hi, Thanks for the information. It looks like we have forgot to change it inside the demo application.
I will take a look at it in the weekend.

**Comment by darkalchemy** [comment]
Thank you. Much appreciated!

**Comment by darkalchemy** [comment]
Thank you
