### ISSUE TITLE
add image url to episodes

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#177]
Feature request:

Is it possible/good idea to add the image url to the episodes method?
Just like the actors/cast method does for the actor image.

Thanks

**Comment by jreklund** [comment]
It's possible. They are all named the same, so you can (for now) trick it to download the high res image, like the cast() function does today.

**Comment by duck7000** [comment]
Okay
Is this something you or @tboothman would add to the episode method?

**Comment by duck7000** [comment]
I tried but i'm not very good at reg ex.. I think that this reg ex should be changed but i don't understand it.

```
$preg = '!<div class="info" itemprop="episodes".+?>\s*<meta itemprop="episodeNumber" content="(?<episodeNumber>-?\d+)"/>\s*'
                      . '<div class="airdate">\s*(?<airdate>.*?)\s*</div>\s*'
                      . '.+?\shref="/title/tt(?<imdbid>\d{7,8})/[^"]+?"\s+title="(?<title>[^"]+?)"\s+itemprop="name"'
                      . '.+?<div class="item_description" itemprop="description">(?<plot>.*?)</div>!ims';
                    preg_match_all($preg, $page, $eps, PREG_SET_ORDER);
```
It should then also match a class="image" <img> i guess

**Comment by duck7000** [comment]
After a lot of trail and error..

[    #========================================================[ /episodes page ]===
    #--------------------------------------------------------[ Episodes Array ]---
    /**
     * Get the series episode(s)
     * @return array episodes (array[0..n] of array[0..m] of array[imdbid,title,airdate,plot,season,episode])
     * @see IMDB page /episodes
     * @version Attention: Starting with revision 506 (version 2.1.3), the outer array no longer starts at 0 but reflects the real season number!
     */
    public function episodes()
    {
        if (!$this->is_serial() && !$this->seasons()) {
            return array();
        }

        if (empty($this->season_episodes)) {
            if (!$this->seasons()) {
                $ser = $this->get_episode_details();
                if (isset($ser['imdbid'])) {
                    $show = new Title($ser['imdbid'], $this->config);
                    return $this->season_episodes = $show->episodes();
                } else {
                    return array();
                }
            }
            $page = $this->getPage("Episodes");
            if (empty($page)) {
                return $this->season_episodes;
            } // no such page
            if (preg_match('!<select id="bySeason"(.*?)</select!ims', $page, $match)) {
                preg_match_all('!<option\s+(selected="selected" |)value="([^"]+)">!i', $match[1], $matches);
                for ($i = 0; $i < count($matches[0]); ++$i) {
                    $s = $matches[2][$i];
                    $page = $this->getPage("Episodes-$s");
                    if (empty($page)) {
                        continue;
                    } // no such page
		        preg_match_all('!<div class="image">\s*(?<img>.*?)\s*</div>\s*!ims', $page, $img);
                    $preg = '!<div class="info" itemprop="episodes".+?>\s*<meta itemprop="episodeNumber" content="(?<episodeNumber>-?\d+)"/>\s*'
                      . '<div class="airdate">\s*(?<airdate>.*?)\s*</div>\s*'
                      . '.+?\shref="/title/tt(?<imdbid>\d{7,8})/[^"]+?"\s+title="(?<title>[^"]+?)"\s+itemprop="name"'
                      . '.+?<div class="item_description" itemprop="description">(?<plot>.*?)</div>!ims';
                    preg_match_all($preg, $page, $eps, PREG_SET_ORDER);
		        $urlIndex = 0;
                    foreach ($eps as $ep) {
			    preg_match('/(?<!_)src=([\'"])?(.*?)\\1/', $img['img'][$urlIndex], $url);
                        $plot = preg_replace('#<a href="[^"]+"\s+>Add a Plot</a>#', '', trim($ep['plot']));
                        $plot = preg_replace('#Know what this is about\?<br>\s*<a href="[^"]+"\s*> Be the first one to add a plot.\s*</a>#ims',
                          '', $plot);

                        $episode = array(
                          'imdbid' => $ep['imdbid'],
                          'title' => trim($ep['title']),
                          'airdate' => $ep['airdate'],
                          'plot' => $plot,
                          'season' => $s,
                          'episode' => $ep['episodeNumber'],
			      'url' => $url[2]
                        );
			    $urlIndex = $urlIndex + 1;

                        if ($ep['episodeNumber'] == -1) {
                            $this->season_episodes[$s][] = $episode;
                        } else {
                            $this->season_episodes[$s][$ep['episodeNumber']] = $episode;
                        }
                    }
                }
            }
        }
        return $this->season_episodes;
    }
](url)

I'm just posting it here to look at because it certainly will not be the best solution.
I will make a pull request but only if you think this is something that makes any sense.
