### ISSUE TITLE
Database and Runtime

### ISSUE THREAD

**Issue by Alexisback** [tboothman/imdbphp#184]
hi, this script is really cool

questions:

1) I am building a cinema database in mysql and php (I'm not a programmer, but just a hobby), is it possible to integrate your script to save the data in the database?

2) Runtime does not save other data,
example
https://www.imdb.com/title/tt0070047/
The Exorcist
Technical Specs
Runtime: 122 min | 132 min (director's cut)

imdbphp saves only
Runtime: 122 min

thanks

**Comment by tboothman** [comment]
1. Not natively, but you can just fetch whatever data you like and store it in a database yourself
2. `runtimes()` is probably what you're after
