### ISSUE TITLE
Original title cannot be scraped

### ISSUE THREAD

**Issue by YesIKnowBut** [tboothman/imdbphp#185]
#### Description
orig_title() returns an empty string. Configuring imdbphp to use a US IP address (1.1.1.1) and "en-US, en" as language had no effect. Debugging information appears further below.

#### Movies / TV-Shows / Person
All movies with an original title. Example: tt0057358.

#### Type
Bug

#### Code
```
$config = new \Imdb\Config();
$config->ip_address = '1.1.1.1';
$config->language = 'en-US, en';
$IMDBTitle = new \Imdb\Title("0057358");
$OriginalTitle = $IMDBTitle->orig_title();
```

#### Expected Results / What do you want to do?
orig_title() should return "Nattvardsgästerna". `<div class="title_wrapper">` in the HTML code pulled from IMDB should include the following:
```
<h1 class="">Winter Light&nbsp;<span id="titleYear">(<a href="/year/1963/?ref_=tt_ov_inf">1963</a>)</span>            </h1>
<div class="originalTitle">Nattvardsgästerna<span class="description"> (original title)</span></div>

```
#### Actual Results / What is happening?
orig_title() returns an empty string. `<div class="title_wrapper">` in the HTML code pulled from IMDB includes the following:
`<h1 class="">NattvardsgÃ¤sterna&nbsp;<span id="titleYear">(<a href="/year/1963/ref_=tt_ov_inf">1963</a>)</span>            </h1>`

**Comment by tboothman** [comment]
Not really enough for me to go on here.
For me this works fine - I get the original title and title as expected in the correct languages.

I get this html which looks exactly the same as yours and it works fine
```
<h1 class="">Winter Light&nbsp;<span id="titleYear">(<a href="/year/1963/?ref_=tt_ov_inf"
>1963</a>)</span>            </h1>
                <div class="originalTitle">Nattvardsgästerna<span class="description"> (original title)</span></div>
```

**Comment by tboothman** [comment]
Just noticed that in your code you're creating the $config object but not passing it into the constructor of `\Imdb\Title`. If that's really your code then that's your problem

**Comment by tboothman** [comment]
If you're doing everything like you've said then you're on your own i'm afraid because i don't have  a computer wherever you are.
Here's -- i think -- the request that you'll be making. Try tweaking stuff until it works
```
curl 'https://www.imdb.com/title/tt0057358/' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0' -H 'Accept-Language: en-US, en' -H 'Referer: https://www.imdb.com/' -H 'X-Forwarded-For: 1.1.1.1' | grep 'class="originalTitle"'
```

**Comment by YesIKnowBut** [comment]
Thanks! I'll mess with the request until it works.
