### ISSUE TITLE
Can't get episodes

### ISSUE THREAD

**Issue by Thomasdouscha** [tboothman/imdbphp#186]
Hi,
It cannot get episodes of https://www.imdb.com/title/tt0088580/

**Comment by tboothman** [comment]
Indeed you can't. The page doesn't load from imdb https://www.imdb.com/title/tt0088580/episodes
I expect it's because every episode is in one season.

**Comment by tboothman** [comment]
There's no support for year based shows either - so even if it did load you'd have a 9000 episode season 1

**Comment by Thomasdouscha** [comment]
But it is not only one much more than twenty-thirty serial. As i understood you mean there is not solution for it?
