### ISSUE TITLE
How to get Photos of the Movie / TV Show

### ISSUE THREAD

**Issue by Machou** [tboothman/imdbphp#187]
Hello

When i use the function `mainPictures()`, i get only 6 photos.

Some series for example have thousands of images, like [Malcolm](https://www.imdb.com/title/tt0212671/mediaindex) for example.

How can I get them back?

Cordially

**Comment by tboothman** [comment]
I suppose that would involve harvesting the images from https://www.imdb.com/title/tt0133093/mediaindex
I just removed mainPictures in v7 so you can't get any images now, but there seem to be 12 pictures on the title page now.

**Comment by Machou** [comment]
Yes, of course there are images on a movie or series file; it would be cool if you could recreate a function similar to ```mainPictures```

Regards

**Comment by duck7000** [comment]
would this a method to get the 12 images on the title page or for all images?

Personaly i would say the 12 images, some movies/tv series have hundreds of images..

**Comment by Machou** [comment]
> would this a method to get the 12 images on the title page or for all images?
> 
> 
> 
> Personaly i would say the 12 images, some movies/tv series have hundreds of images..

what would be nice is a function to have the 12 images of the form as well as a function to have all the images of the form.

Oki some cards have thousands even :)

**Comment by duck7000** [comment]
I made a PR for the 12 images
