### ISSUE TITLE
Method Title::releaseInfo crash when run on PHP 7.4 cli

### ISSUE THREAD

**Issue by riverstore** [tboothman/imdbphp#194]
#### Description

Hi, I found that Method `Title::releaseInfo` crash when run on PHP 7.4 cli (Ubuntu 20.04 LTS), I test in web it run fine. I debug and see that this line cause the error
[if (empty($page)) {](https://github.com/tboothman/imdbphp/blob/eebdd02ba9079726cc7ac07ebf48d6e8ee9268cc/src/Imdb/Title.php#L2538)

I can print the $page variable value via log (`$this->logger->error($page);`) but when I use function like `strlen` it's crash.

I checked on some IMDB ID and still see that problem.

Please check it. Thank a lot.

Edit: The file php.ini are same for cli and php-fpm

**Comment by jreklund** [comment]
Could you provide a short code example so we can try to replicate it. With the IMDb id you have tried.

**Comment by riverstore** [comment]
Hi, Here is the id `335266`. It don't show any error message, I turn debug to true on config and on the code and on the php.ini

`error_reporting(E_ALL);'
'ini_set('display_errors', True);`
`public $debug = true;`

Regard.

**Comment by jreklund** [comment]
Hi, I just ran the following test, without any issue. So I can't replicate it. This is with a complete fresh Ubuntu 20.04 LTS, no upgrade.

Only installed:
`sudo apt-get install php7.4-cli php7.4-curl php7.4-xml`

```
jreklund@ubuntu20:/var/www/imdbphp/demo$ php7.4 --version
PHP 7.4.3 (cli) (built: Mar 26 2020 20:24:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

```php
<?php
require __DIR__ . "/../bootstrap.php";

$config = new \Imdb\Config();
$movie  = new \Imdb\Title(335266, $config);
var_dump($movie->releaseInfo());
```

**Comment by riverstore** [comment]
Hi, I test your code and it run fine. It may problem from me.
Thank a lot for your help.
Regard.

**Comment by riverstore** [comment]
Hi, 

I just found the problem is that I use `spl_autoload_register`, now I can run the code after removed `spl_autoload_register`.

Regard.
