### ISSUE TITLE
Title object does not honor cache path set via $config parameter

### ISSUE THREAD

**Issue by IzzySoft** [tboothman/imdbphp#195]
#### Description
First thanks for keeping my baby alive, Tom! I recently revived my good-old [phpVideoPro](https://github.com/IzzySoft/phpVideoPro) and was surprised how easy I could re-enable *IMDBPHP* there – thanks to the fact you've kept the "returned structures" compatible all the time :smiley:

Now for my issue: I've noticed that if I pass specific cache settings (especially the cache dir) via the config parameter, that was respected for `TitleSearch` – but not for `Title`. The latter only respected them when directly applied to the `Title` object:

```php
$config = new \Imdb\Config();
$config->cachedir = $cachedir;
$title = new \Imdb\Title($movieid,$config);
// no way, explicitly needs:
$title->cachedir = $cachedir;
```

Is that intended? It's certainly not expected. It's of course good one can also override it that way, but if it accepts a `$config` as parameter, it should also respect it I guess :wink:

#### Type
Bug

#### Code
See above.

#### Expected Results / What do you want to do?
IMDBPHP using the cache directory specified.

#### Actual Results / What is happening?
IMDBPHP ignores the cache path specified to `$config` and uses its internal defaults (I did not check whether specifying a directory via `900-localconf.ini` would have any effect).

**Comment by jreklund** [comment]
Hi IzzySoft, I will answer a couple of your questions if that's okay. :-)

Your problem seem odd. As it just passes it down to `MdbBase`, same class that `TitleSearch` uses.

You can set the following without any issue, so it's weird `cachedir` would not be allowed from `Title`.
```
// I set these to \Imdb\Title
$config->language
$config->ip_address
$config->debug
```

I does read cache settings from `900-localconf.ini`. I have set it there, so people don't change it from the application configuration.
```
cachedir = 'cache/'
```

Have you tried to set any other configurations settings to your `Title`, just for the sake of things?

**Comment by IzzySoft** [comment]
Thanks for your fast response, @jreklund! And no, I don't use the `9xx-localconf.ini` in this case. To give some background: With the default settings of PVP, configuration is left to IMDBPHP (including the `.ini` of course). But I want to allow the admin to override cache settings (to use an app-specific location; that was originally configured there when I started maintaining IMDBPHP those many years ago) – plus allow setting e.g. the language per-user. So I have to set the cache location directly as described above, to override IMDBPHP's config.

I've no idea whether the language setting has any effect (except maybe for title search); I didn't yet encounter any record with e.g. German summary or comments despite of using `de-DE,de,en`. I can live with how IMDBPHP works concerning the above issue (I simply apply the settings on the `Title` object again). I just found it odd and thus thought to report it.

If it matters: Before those lines of code I quoted, I simply loaded the `bootstrap.php`. The only difference I see on a quick glance is that `Title`  has its own constructor, while `TitleSearch` has not. Should not make a difference here though, as `Title` simply passes all arguments to `parent::__construct()`…

No idea, and low prio. As indicated, I found a work-around for my application.

PS: I still wonder how cache deals with similar searches in different languages. If I search for a localized German title, and the next person for the same phrase as French, the latter would get my German results, right? Not a big deal in most cases, just thinking aloud…

**Comment by tboothman** [comment]
Fairly sure your code isn't the same as your sample code, because it doesn't make sense.
The only way $title->cachedir would do anything is if you haven't passed in $config to the Title class.
In the constructor of mdbbase there's this code:
```
$this->config = $config ?: $this;
$this->logger = empty($logger) ? new Logger($this->debug) : $logger;
$this->cache = empty($cache) ? new Cache($this->config, $this->logger) : $cache;
```
If you'd passed in a $config the cache's config would be that object so changing $this would do nothing.
I wish i'd just bitten the bullet and completely rewritten the inheritence from the Cache class, it's a little weird how it is now.

**Comment by tboothman** [comment]
Yup, found it: https://github.com/IzzySoft/phpVideoPro/commit/bcb0b93ae0a02c38c8749534f6e3b2e34d65fb87#diff-abee809a63deadad497b6aefbd4e48a7R228
You've passed $config (which doesn't exist) to the constructor after setting up $iconfig

**Comment by tboothman** [comment]
Welcome back, btw :)
I've been away from PHP for ~2 years too, and I've not even been watching many movies lately. Jreklund's been doing most of the maintence since v6 ~2 years ago. There's not much to change with this library any more really. If people stopped changing Hayao Miyazaki and the Matrix's imdb pages and breaking the tests i wouldn't look at it much.

**Comment by IzzySoft** [comment]
Uh, a typo then – apologies! And thanks for spotting! Tested and confirmed, works as expected, [committed and pushed](https://github.com/IzzySoft/phpVideoPro/commit/fe0880f58ce07f575b9352b1d91328e42dba7203) (ouch, two errors at the same time). I was already going nuts trying to understand what happened :rofl:

Thanks for the warm welcome! And yeah, I remember: in the last 2 years I maintained the lib, 90% of the work was fixing what they broke changing the site. But man am I glad you two kept it up. Just started adding movies I collected in the last ~10 years. I'd go mad doing that manually!

**Comment by jreklund** [comment]
Good that it all worked out in the end!

> PS: I still wonder how cache deals with similar searches in different languages. If I search for a localized German title, and the next person for the same phrase as French, the latter would get my German results, right? Not a big deal in most cases, just thinking aloud…

Unless you clear the cache when a person changes language, it will be German still. So it's an application setting.

**Comment by IzzySoft** [comment]
Thanks for clarifying! Would be hard indeed with the possibility of someone having added four lang-prefs, another one five, and the overlap is X. I don't want to think of all possible variants :laughing: Should a solution arise, I'd be curious. Should be a rare case, though, that two movies have the same spelling for different names.

**Comment by tboothman** [comment]
If multi language is required by the application it would make sense for that application to deal with it. There's not a great deal in imdb that is localised (title, release date, rating (PG, 15 etc)) and i believe that every location's data is retrievable for those.

A slightly dodgy way to lean on the library as a database would be to alter the cache key to include a language (or whatever the setting is). You could extend the cache class and override its key creation method -- it has access to the config class so could include anything

**Comment by IzzySoft** [comment]
In my experience, the only part where localization happens (if it does at all) is TitleSearch, if you're searching for a localized title this probably increases your chance of your language being considered in the result order. I didn't yet encounter any German content for example, despite of using `de-DE,de,en` for language. Rating is language independent, too (one always gets all ratings returned, and localization doesn't even effect order).

So honestly, I see no urgency here: the effort currently is by far not worth the outcome. But thanks for thinking about!
