### ISSUE TITLE
IMDB rating

### ISSUE THREAD

**Issue by mpol12** [tboothman/imdbphp#197]
Hi,
could you verify the issue I'm facing?
I'm not getting the rating of movies.
Take for example ID tt7150512.. I'm getting no rating.
...

**Comment by paxter** [comment]
Works fine for me.

```
$imdb = new \Imdb\Title(7150512);
echo $imdb->rating();
```

Result:
```
7.1
```

**Comment by mpol12** [comment]
Now it works for me too...!?!?!?!?
Thank you for looking into this.
