### ISSUE TITLE
Undefined offset: 1 at imdbphp/imdbphp/src/Imdb/Title.php:2995

### ISSUE THREAD

**Issue by Fossil01** [tboothman/imdbphp#198]
#### Description
Get this error in my logs. Line 2995 is:   `$this->jsonLD = json_decode($matches[1]);` so I guess the $matches array does not contain that offset. I guess it could be fixed by checking if it exists first?

#### Type
Bug

#### Code
```php
    protected function jsonLD()
    {
        if ($this->jsonLD) {
            return $this->jsonLD;
        }
        $page = $this->getPage('Title');
        preg_match('#<script type="application/ld\+json">(.+?)</script>#ims', $page, $matches);
        $this->jsonLD = json_decode($matches[1]);
        return $this->jsonLD;
    }
```

**Comment by tboothman** [comment]
What method are you using and on which film? It's likely something else is going on as all the title pages have the json-ld on them

**Comment by Fossil01** [comment]
```
[stacktrace]
#0 /var/www/REMOVED/vendor/imdbphp/imdbphp/src/Imdb/Title.php(2995): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/REMOVED/vendor/imdbphp/imdbphp/src/Imdb/Title.php(467): Imdb\\Title->jsonLD()
#2 /var/www/REMOVED/Blacklight/Movie.php(910): Imdb\\Title->rating()
```

rating() is used.

I don't know which movie but it must be quite a few because it appears a lot in my logfile.

**Comment by tboothman** [comment]
I wonder if  #197 is related

**Comment by Fossil01** [comment]
Have no clue to be honest. It's still happening as of now. Maybe return 0 for the rating if it cant find any?

**Comment by tboothman** [comment]
I wonder if you've got some sort of error page cached .. and either the error page was returned with a 200 status code or the request class didn't throw an exception like it should have

**Comment by Fossil01** [comment]
I don't think it caches anything. I'll have another look tommorrow, might add some logging code and see what's going on.

**Comment by vlahde** [comment]
I get similar error when trying to import this title https://www.imdb.com/title/tt0190733/

**Comment by jreklund** [comment]
> I get similar error when trying to import this title https://www.imdb.com/title/tt0190733/

Can't personally replicate it with the demo application. rating() can be downloaded on that one. And other data based on json as well.

**Comment by ThornstromDeveloper** [comment]
This issue seems to have been temporary at the source, I had this issue for a while and now it's gone.
