### ISSUE TITLE
New version of IMDB

### ISSUE THREAD

**Issue by GeorgeFive** [tboothman/imdbphp#206]
You guys seen the new version of the site?  Pretty different.  Anybody started on an overhaul of the script?

https://help.imdb.com/article/issues/GMWASETVPLJYXEZE?ref_=tt_optin_banner_inf

**Comment by paxter** [comment]
Hm, intereristing. Indeed this could break a lot of things.

**Comment by tboothman** [comment]
https://github.com/tboothman/imdbphp/releases/tag/v7.0.0
