### ISSUE TITLE
episodes() ?!

### ISSUE THREAD

**Issue by Thomasdouscha** [tboothman/imdbphp#214]
Hello,

episodes() function is not getting info of episodes if the serial tv show's based on years not seasons.
For example : https://www.imdb.com/title/tt0388629/?ref_=ttep_ep_tt
This is very popular anime serial. It was based season and now they changed to years.
Is there any way to get episodes info in such condition?

Thanks

**Comment by tboothman** [comment]
Relates to #186 
Do you have any thoughts on how this would work?
I've not used imdb for tv and its support for it seems less than complete.

It looks like tv episodes generally have a season and episode set (neighbours seems to have some unknown) and then they've added in functionality to browse episodes by year of air date.

What distinguishes a show that genuinely has one season to a long lasting unseasoned show?
e.g. https://www.imdb.com/title/tt0303461/ has 1 season but 2 years. It's a seasoned show.
https://www.imdb.com/title/tt0088580/ has 1 season and 1 unknown season and many years. It's not a seasoned show.

Is the grouping of results by season important? Should/could it be by year if it's somehow known it's a year show?

The current code would in theory work if the imdb pages imdb links to actually returned results. Fetching season 1 of one piece will return every single episode .. but the page won't load.
Maybe it doesn't matter?
https://www.imdb.com/title/tt1027544/ has unknown years and unknown seasons.

Perhaps could flip around the episode fetching to be by year. Mostly the number of years and seasons is the same e.g. https://www.imdb.com/title/tt0306414/ so it shouldn't be less efficient and at least it would load for big seasons.

**Comment by Thomasdouscha** [comment]
No it is not important. it can be year based too. Does not matter for me. But episodes() func cannot get episodes info in such condition.

**Comment by tboothman** [comment]
Should be fixed now #242
