### ISSUE TITLE
sometimes original_title missing

### ISSUE THREAD

**Issue by dddesign** [tboothman/imdbphp#220]
check this with the demo of imdbphp 6.5.0:
with search by imdb id of movie I get all the information but sometime the orginal title is missing. with one of the next load of uncached data original title will show up. check it yourself: http://.../imdbphp/demo/movie.php?mid=4623812
is this a bug or a problem of imdb page/api?
thanks for any hints

**Comment by paxter** [comment]
Working fine for me.

Title: The Wasted Times
Original Title: 罗曼蒂克消亡史

**Comment by ExYuSubs** [comment]
someone who has problems with the poster, on my page some of the newer titles can't "scratch" image from movie / tv show

**Comment by GeorgeFive** [comment]
I'm also getting this issue with the country.  Sometimes it will not load the country, sometimes a refresh will fix it.  Not consistent at all, but it has been happening fairly often.

**Comment by DaanDeJong2001** [comment]
Can you check in your cache folder the data received from IMDB? 
Is it delivering the content as JSON? Search for `<script type="application/ld+json">`.

If so, I think this is a duplicate to #218 . Maybe IMDB is not delivering the new content to all. Could be some slow roll-out or a/b testing.

**Comment by M0H4MM4D0UTIS** [comment]
> I'm also getting this issue with the country. Sometimes it will not load the country, sometimes a refresh will fix it. Not consistent at all, but it has been happening fairly often.
> 
> Also, at least once I've had a TV series load the series credits instead of the episode list. Again, a refresh fixed this.
> 
> Never had these intermittent issues like this, so I wonder if it's something behind the scenes on their end.

I have this problem too
At the same time the following problem:
https://github.com/tboothman/imdbphp/issues/218

**Comment by M0H4MM4D0UTIS** [comment]
These problems are due to the new version of the imdb site:
https://help.imdb.com/article/issues/G6HYBHAA9EHPXA6G

New version enabled for some countries.
You may be able to escape the new version by setting the language to German or French!
sample: fr-FR OR de-de
`$config = new \Imdb\Config();
$config->language = 'fr-FR';
$title = new \Imdb\Title(3110958, $config);`

I am reviewing and fixing the problems and soon the changes will be marged with the main repository.
You can follow the changes through the following link:
https://github.com/M0H4MM4D0UTIS/imdbphp/commits/master

**Comment by paxter** [comment]
> New version enabled for some countries.
> You may be able to escape the new version by setting the language to French!
Is it known which countries are affected and when other will follow?

**Comment by duck7000** [comment]
@M0H4MM4D0UTIS 
Great that you are working on this but what i really misses in this conversation is the input from the maintainer of this project

**Comment by M0H4MM4D0UTIS** [comment]
> @M0H4MM4D0UTIS
> Great that you are working on this but what i really misses in this conversation is the input from the maintainer of this project

no I do not think so. You may be able to understand this by testing all languages!
languages code:
http://www.lingoes.net/en/translator/langcode.htm

**Comment by ExYuSubs** [comment]
@M0H4MM4D0UTIS so what you think is solution for that problem?
I can't solve it on some language at all ....

**Comment by M0H4MM4D0UTIS** [comment]
> @M0H4MM4D0UTIS so what you think is solution for that problem?
> I can't solve it on some language at all ....

Now with a few refresh times, you may see the old version of the site and the information will be extracted successfully
This has been tested!

I wrote a simple code to identify the new and old version of the site and now you can use it with a while loop to refresh:
`public function detect_new_version_imdb()
    {
        $page = $this->getPage('Title');
        if (stripos($page, 'xmlns:og="http://opengraphprotocol.org/schema/"') !== false) {
            return true;
        }
        return false;
    }`


The changes to the new version of the site are enormous. I know that keeping up with these changes takes time and requires the cooperation of others

**Comment by tboothman** [comment]
If you want to prolong the inevitable you can force the request to be in a session that's using the old layout.
Add `$this->addHeaderLine('Cookie', 'session-id=130-4612460-2590226; session-id-time=2082787201l; ubid-main=133-1270118-7584829; session-token=i6MkJR0I+3m+vpt1FWYRs/FEGE4qKt9tVJOH3xOOiCM2RMXYP7ae97z7k1nI7A8lwcxqk2CzcNqkHtTZZIdYqFTLKnMvRtMdkg9GivmTPMhN05L9E/1D0WSo0NavIa+5cEY68FwU4hjr5PdJ4Ixeqh3yy8cHLRHj7aGegt6mx4MslreCNS1MJJyb4fqln8w1');` to the constructor of `Imdb\Request`.
Not 100% sure what it does ... might stick your language to en-GB too.

**Comment by tboothman** [comment]
I've released that as v6.5.1

**Comment by duck7000** [comment]
Mm interesting, i used to get the choice for the new or old version but since about a week or so i don't get that choice anymore and always get the old version.
So the question is will imdb use the new one or keep remaining the old one, there is a lot of hate against the new version so maybe they have listen..

**Comment by M0H4MM4D0UTIS** [comment]
> If you want to prolong the inevitable you seem to be able to turn off the new layout still.
> Add `$this->addHeaderLine('Cookie', 'beta-control=""');` to the constructor of `Imdb\Request`.
> Who knows how long that'll work for .. but short of deleting that cookie I can't actually see the new layout or find a way to see it in my browser

I've tested it and it does not work!

**Comment by tboothman** [comment]
Well it works on my computer and on travis .. I have no other way to test it

**Comment by paxter** [comment]
Maybe it's related to geolocation of the origin ip address?

**Comment by M0H4MM4D0UTIS** [comment]
> Maybe it's related to geolocation of the origin ip address?

Yes. I think it depends on that

**Comment by ExYuSubs** [comment]
@tboothman that new solution works in my case, I use 6.5.1 and it works. Thanks a lot
@M0H4MM4D0UTIS my VPS machine have a static IP address and is located in USA and works like a charm

**Comment by DaanDeJong2001** [comment]
@M0H4MM4D0UTIS please try removing the cached entry. See your config for exact location. Otherwise library will not request the old version.
