### ISSUE TITLE
movie photo doesn't work properly

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#223]
Movie photo only gives half of the image?
![Screenshot from 2021-07-03 16-59-13](https://user-images.githubusercontent.com/15360048/124358341-1b4c9500-dc20-11eb-9775-5784451a73ef.png)

That could be considerd as a upgrade because it didn't work at all but i don't understand why this happens?

**Comment by duck7000** [comment]
Mm it looks like there is a mixed up issue here, this half image above is the preview image from the video, not the main image that is shown on the left.

**Comment by M0H4MM4D0UTIS** [comment]
I did some tests
There seems to be a problem extracting the thumb. But the original image to be extracted properly.
sample for this movie:
https://www.imdb.com/title/tt0092610/

main poster:
https://m.media-amazon.com/images/M/MV5BNmU5YzQyODEtZjY4MC00ZDA2LTk1YTItZmNiN2MyMWU3MGUzXkEyXkFqcGdeQXVyNjMwMjk0MTQ@._V1_.jpg

thump extracted:
https://m.media-amazon.com/images/M/MV5BYjI3NzIxNDgtMTlmNS00YjJkLThjNzItNmJlMDI5ODM5ODAzXkEyXkFqcGdeQXVyMTY3ODc0NjM@._V1_QL75_UY207_CR174,0,140,207_.jpg

thumb Extracted incorrectly


I rewrote it with xpath and it was solved:
https://github.com/tboothman/imdbphp/pull/224/commits/bb32772a0a0abc5e4f99e7068d768e97b327eb9f

**Comment by duck7000** [comment]
thanks a lot!
Hope this get merged soon.
