### ISSUE TITLE
orig_title not work

### ISSUE THREAD

**Issue by sbdvhjrfw** [tboothman/imdbphp#227]
#### Description
orig_title not work, i tried lot of time, but new version orig title not work.. :-/

#### Type

Bug

<img width="1395" alt="Képernyőfotó 2021-07-04 - 8 33 53" src="https://user-images.githubusercontent.com/33731226/124375471-a5d5d880-dca2-11eb-940f-f90f0ef0784b.png">

**Comment by tboothman** [comment]
It didn't but it does in master. Trying to make sure everything works before doing another release. See #221
