### ISSUE TITLE
Problem with Kung Fu - TV Series

### ISSUE THREAD

**Issue by guardiaopt** [tboothman/imdbphp#239]
I just tested version 7 and the episode page is not obtained in the following TV Series:

https://www.imdb.com/title/tt7475590/

Does anyone else have the same problem?

**Comment by M0H4MM4D0UTIS** [comment]
i fix this on https://github.com/tboothman/imdbphp/pull/240

**Comment by tboothman** [comment]
What do you mean by 'the episode page'? What method?

**Comment by guardiaopt** [comment]
For example:
....
$imdbid=7475590;
$config = new \Imdb\Config();
$config->language = 'en-US,en';
$movie = new \Imdb\Title($imdbid, $config);
$seasons = $movie->episodes();
print_r($seasons);

No results are returned and no file title.tt7475590.episodes.season=1 is created in the cache folder.

**Comment by tboothman** [comment]
Oh yea I see why it's not working. `Title::seasons()` looks like it doesn't work for single season shows ... and despite explicitely calling out in the many tests for episodes() that they were all for multiseason shows there's no tests for single season shows :S
