### ISSUE TITLE
SSL errors up to php 7.4

### ISSUE THREAD

**Issue by mesa57** [tboothman/imdbphp#247]
#### Description
Curl up to 7.4 gives SSL errors on imdb url.

I would like to have an option in config to put off ssl verification.
E.g. CURLOPT_SSL_VERIFYPEER to false

#### Movies / TV-Shows / Person
Any imdbid

#### Type
Feature request

#### Expected Results / What do you want to do?
Working requests to imdb without changing [curl] options in php.ini

#### Actual Results / What is happening?
Exception due to SSL error

**Comment by jreklund** [comment]
This is something that won't be implemented. You can read more about it in #76.

**Comment by mesa57** [comment]
Thanks for the quick answer. I understand it is a windows only problem ? If this not occurs under linux, it's not a big problem as most of our users are Linux/NAS users. But my DEV environment run's under windows.
Strange thing is an other package doesn't seem to have that problem. It looks being tied to Curl.

**Comment by jreklund** [comment]
It's a Windows only problem as this ain't something that gets bundled with PHP as there are no native way of updating it under Windows. If you don't experience this with other libraries, I guess they don't validate the certificate.

I always forget to set this myself as I mainly use Windows for development on my home PC. I haven't bothered to set up a Virtualbox just for imdbphp.

**Comment by mesa57** [comment]
Ok, thank you. Closing this enhancement for now 😄
