### ISSUE TITLE
Parsing runtime is not working on the linked page

### ISSUE THREAD

**Issue by kakaska** [tboothman/imdbphp#252]
Parsing the runtime is not working on the following page: tt5884196

The runtime on the page is "2h"

Thank you

**Comment by Thomasdouscha** [comment]
This not main page. Just episode page.
![image](https://user-images.githubusercontent.com/43930732/126362903-95ef2c4a-bcba-48c2-a8b9-95ae233e1a12.png)
main page get running time very well.

**Comment by duck7000** [comment]
@kakaska  is this issue still relevant? If not can you close this issue?
I'm not sure this library works on a specific episode page but i could be wrong
