### ISSUE TITLE
Issue with utf8_decode/umlauts on short cast output

### ISSUE THREAD

**Issue by paxter** [tboothman/imdbphp#262]
I just noticed that umlauts on cast names are broken. I don't know if it's related to my software or os I'm using. If it's working for you, I'll close this issue.

It's line 1724 in `Title.php` which cause the issue for me: https://github.com/tboothman/imdbphp/blob/e6e61e2cf70cda0a64c03f7d9259b18762bd12b8/src/Imdb/Title.php#L1724

After removing the line with `utf8_decode()` it's working fine.

I used [tt15105300](https://www.imdb.com/title/tt15105300/) for testing.

With utf8_decode(): Elke K�pping
Without: Elke Köpping

Do we need `utf8_decode()` function(s) in the code? I don't know for what reason these functions are used.

**Comment by tboothman** [comment]
Looks like a mistake to me. Titles are utf8, so it'd be weird for actor names to use a different character set

**Comment by duck7000** [comment]
In the same method, line 1746 there is also utf8)decode used for year? That shouldn't be there as well?
