### ISSUE TITLE
spouse()

### ISSUE THREAD

**Issue by Thomasdouscha** [tboothman/imdbphp#265]
Hello,

Person object spouse() function is not working. It doesn't get data of spouse.

Thanks

Thomas

**Comment by Thomasdouscha** [comment]
So is it not important?

**Comment by duck7000** [comment]
Well personally i don't use that method.

And i don't think it will ever be fixed here, there is not been any reaction in months and the last commit is from October 2021..
At least i'm not going to do any more work to this repo, sorry.

**Comment by Thomasdouscha** [comment]
I really really sorry to hear that. 
I wanna know whats happening here. Nobody is going to support this repo anymore? I hope it is not likr this.
Thanks four your answer duck7000

**Comment by duck7000** [comment]
I really don't know
I created several PR requests here, a few are communicated about but that stopped suddenly months ago
All other PR i didn't get a single response on so i took a drastic step and removed them all.

That doesn't mean that the maintainers are not going to do any work on this and i sure hope they will continue.

So yes, i'm in the same "boat" as you:  I too want to know whats happening here..?

**Comment by Thomasdouscha** [comment]
Maybe "drastic step and removed them all" is not way for handling the issues. Now it's hard times for everyone, even for the whole world. Pandemic, the prospect of economic crises and wars, large and small, seriously affects people's order and life. Maybe they were also affected by these problems. I hope they are fine and all is well. You did your best, you worked hard. I think it would be better if you put those PRs you removed back in it. Of course, you know better about what to do. I thank you for your efforts. I hope your efforts continue.

**Comment by duck7000** [comment]
I understand your concerns but for me there is no point in putting the PR's back if non of the maintainers are paying attention to them?
Johan Eklund is the only one that did responded, communicated well about it and gave good tips. But he doesn't, for reasons i don't know, respond any more in months.

I'm doing all the work, for bugs and rewrites of some methods, but if there is no response, or at least not anymore, there is no point.
I can't add those pr myself other than in my own fork.

Honestly i do want to put those PR's back if i would know that the maintainers are willing to even look at it.
In one case tboothman asked for help, I did respond to that request, even with a PR but he not even bothers to give a response to the issue he created, not once. I don't understand this and makes me frustrated

**Comment by duck7000** [comment]
I added back a few PR's 
And now we have to wait and see

**Comment by Thomasdouscha** [comment]
It is better way, thanks

**Comment by duck7000** [comment]
@Thomasdouscha 
Can you give me a example movie en witch data this method should return? I'm trying to fix it for you but i don't have a clue what data should returned.

**Comment by Thomasdouscha** [comment]
I used method:
`$person->spouse();`
Also you can looking for demo directory person.php of spouse part. My code is very similar. Let you check it please.

**Comment by duck7000** [comment]
I used spouse method, it returns nothing, but what should it return is the question?
It should include name and imdbid but what about the rest?

**Comment by Thomasdouscha** [comment]
mate name imdb_id married date if yes divorced date and children count. I will check my code later.

**Comment by Thomasdouscha** [comment]
![image](https://user-images.githubusercontent.com/43930732/155563222-4f8b8be3-1f5e-44b9-bfee-4269190ccc93.png)

Charles Bronson from imdb page.

**Comment by duck7000** [comment]
Ah oke that is de info i was looking for, thanks!
I will give it a try, no guaranties

**Comment by Thomasdouscha** [comment]
Data looks like as past. I think because of small change it does not work. May be to fix it easy or not.
Thanks

**Comment by duck7000** [comment]
well it is not an easy fix, and i doubt it ever has been functioned at all. This method is full of code that can't be working on the current bio page. That page has been changed a lot if the old code actually did work.
I'm still trying though

**Comment by Thomasdouscha** [comment]
I hope that  will be sucess.

**Comment by duck7000** [comment]
Still working on this, it may take some time, i have more PR's that i'm working on.
And that is a good thing! Tboothman has already reviewed 2 off them and eventually approved!
I'm very happy about that!

**Comment by Thomasdouscha** [comment]
It's good!

**Comment by duck7000** [comment]
I finally managed to get it fixed (i hope) and made a PR
so @Thomasdouscha check it out and let me know if there are any problems left.

**Comment by Thomasdouscha** [comment]
Thanks a lot. i will test it tomorrow!

**Comment by Thomasdouscha** [comment]
No it does not

**Comment by duck7000** [comment]
what is the problem?

**Comment by Thomasdouscha** [comment]
![image](https://user-images.githubusercontent.com/43930732/159533236-06e75ecc-714a-41a8-b50f-fc7936509d21.png)

İt is simply return empty. When i update the person data there is no spouse information.
what about person of demo in imdbphp? is it working?

**Comment by Thomasdouscha** [comment]
![image](https://user-images.githubusercontent.com/43930732/159540491-6713d105-5631-4f11-87b1-ceca83b65705.png)
It works !!!
I will try 5-6 six other person

**Comment by Thomasdouscha** [comment]
But wife name there is not. Marriage dates and children and marital status ok. JUst wife names ?

**Comment by Thomasdouscha** [comment]
![image](https://user-images.githubusercontent.com/43930732/159541428-3c37cb22-4843-46e4-b99a-b460e3663656.png)
as you see in database there aren't wive names!

**Comment by Thomasdouscha** [comment]
I tested some persons and the result: Wife name return is empty! other datas are ok!

**Comment by duck7000** [comment]
Wow.. slow down a bit and please stop using so much ! it feels like shouting

First i didn't touch anything in the demo pages so i don't know if that will work.

And second i think there is something wrong in your application? Because i get all info from charles bronson?
This is my output from method spouse() in person.php and i call it like this:

```
$imdb = new \Imdb\Person('0000314');
$results = $imdb->spouse();
var_dump($results);
```

> array(3) {
>   [0]=>
>   array(6) {
>     ["imdb"]=>
>     string(7) "0917331"
>     ["name"]=>
>     string(9) "Kim Weeks"
>     ["from"]=>
>     array(4) {
>       ["day"]=>
>       string(2) "27"
>       ["month"]=>
>       string(8) "December"
>       ["mon"]=>
>       string(2) "12"
>       ["year"]=>
>       string(4) "1998"
>     }
>     ["to"]=>
>     array(4) {
>       ["day"]=>
>       string(2) "30"
>       ["month"]=>
>       string(6) "August"
>       ["mon"]=>
>       string(2) "08"
>       ["year"]=>
>       string(4) "2003"
>     }
>     ["comment"]=>
>     string(9) "his death"
>     ["children"]=>
>     string(0) ""
>   }
>   [1]=>
>   array(6) {
>     ["imdb"]=>
>     string(7) "0409866"
>     ["name"]=>
>     string(12) "Jill Ireland"
>     ["from"]=>
>     array(4) {
>       ["day"]=>
>       string(1) "5"
>       ["month"]=>
>       string(7) "October"
>       ["mon"]=>
>       string(2) "10"
>       ["year"]=>
>       string(4) "1968"
>     }
>     ["to"]=>
>     array(4) {
>       ["day"]=>
>       string(2) "18"
>       ["month"]=>
>       string(3) "May"
>       ["mon"]=>
>       string(2) "05"
>       ["year"]=>
>       string(4) "1990"
>     }
>     ["comment"]=>
>     string(9) "her death"
>     ["children"]=>
>     string(1) "1"
>   }
>   [2]=>
>   array(6) {
>     ["imdb"]=>
>     string(0) ""
>     ["name"]=>
>     string(15) "Harriet Tendler"
>     ["from"]=>
>     array(4) {
>       ["day"]=>
>       string(2) "30"
>       ["month"]=>
>       string(9) "September"
>       ["mon"]=>
>       string(2) "09"
>       ["year"]=>
>       string(4) "1949"
>     }
>     ["to"]=>
>     array(4) {
>       ["day"]=>
>       string(0) ""
>       ["month"]=>
>       string(0) ""
>       ["mon"]=>
>       string(0) ""
>       ["year"]=>
>       string(4) "1967"
>     }
>     ["comment"]=>
>     string(8) "divorced"
>     ["children"]=>
>     string(1) "2"
>   }
> }

I notice that you use, i guess, turkisch language? I only tested this with the standard English language in imdbphp config. I don't know if that makes any difference though

**Comment by Thomasdouscha** [comment]
may be i did not get fully true your person file. My code is simple ->spouse() and there is no data in database. Can you send me person.php file?

**Comment by Thomasdouscha** [comment]
no it is not about turkish i can get everything except this wife name.

**Comment by duck7000** [comment]
Just replace the existing method with the one from my PR, nothing else changed
or copy the whole person.php from my PR
but here is my file
[Person.zip](https://github.com/tboothman/imdbphp/files/8328078/Person.zip)

**Comment by Thomasdouscha** [comment]
Thanks a lot. There is no problem! It works very well!
![image](https://user-images.githubusercontent.com/43930732/159586470-ae708d6b-0f93-480d-aba9-f9cc486fdc62.png)

**Comment by duck7000** [comment]
Thanks, glad it works. It was a pain in ass to get it working.
Now we have to hope this will get merged.

**Comment by Thomasdouscha** [comment]
There is one bug!
If the person has not spouse data for example single never married and child , spouse() has crashed. Otherwise i mean the person has spouse data , it works perfectly

**Comment by Thomasdouscha** [comment]
temprorily i fixed "try{ $spouse = $imdbperson->spouse();}catch (\Exception $e) {$spouse=""; }" like this until you fix it.

**Comment by duck7000** [comment]
Mm I'm not surprised that there still are bugs

Can you give me a example of where it did not work, your description is not clear enough.
And what do you mean by "crash"?

**Comment by duck7000** [comment]
With this person: David Bennent (0000908) i get empty array just like it suppose to do?
This person has no spouse data available, i did check that, but there may be other circumstances that i didn't check perhaps

```
array(0) {
}
```

**Comment by Thomasdouscha** [comment]
try{ $spouse = $imdbperson->spouse();}catch (\Exception $e) {$spouse=""; }
what crash means this code shows i think. spouse() funtion gives error  some cases. I will give you some persons as exsamples.
[https://www.imdb.com/name/nm2956530](url)
[https://www.imdb.com/name/nm8033456](url)
these persons doesn't have spouse history. So with kind of persons spouse func should gives return null or "" soethings empty. but it does not give it. That is bug in my oppinion so as a result in such cases code broken and gives error.

**Comment by duck7000** [comment]
Ah okay you're right, in the above cases there is no family part on the bio page, so there will be this error:
Trying to get property 'nodeValue' of non-object

I will try to fix that

**Comment by Thomasdouscha** [comment]
Thanks a lot

**Comment by duck7000** [comment]
It is fixed in PR, test it out please

**Comment by Thomasdouscha** [comment]
Great! i will remove that code try{ $spouse = $imdbperson->spouse();}catch (\Exception $e) {$spouse=""; } and will test now

**Comment by Thomasdouscha** [comment]
and i need to have revised person.php

Sorry i dont use git and i dont know how to do.

**Comment by duck7000** [comment]
Is it so hard to just copy the whole method from PR and paste it in your file?
[Person.php.zip](https://github.com/tboothman/imdbphp/files/8349973/Person.php.zip)

**Comment by Thomasdouscha** [comment]
Ya you are right. I should learn how to do with git.
now it is okay it works perfectly

**Comment by duck7000** [comment]
great, if you have the change would you test it even more to make sure it works in all cases?

**Comment by duck7000** [comment]
And if so add it to your issue and ask to be merged, otherwise it might got forgotten and is all my work for nothing.

**Comment by Thomasdouscha** [comment]
In our website thousand member using it. So if there is any bug we will learn very qucikly. Nobody make a report bug about person card till now. So it is working perfectly .

**Comment by Thomasdouscha** [comment]
tomorrow i will do that. It wşll not be for nothing

**Comment by Thomasdouscha** [comment]
Thanks, My last comment for pr is okay! Please let you it to merge with new revision.
