### ISSUE TITLE
Keyword method returns empty array

### ISSUE THREAD

**Issue by jcvignoli** [tboothman/imdbphp#277]
#### Description
Keyword method returns empty array

#### Movies / TV-Shows / Person
Happens i.e. with 0062622 (2001, a space odyssey)

#### Type
Bug: 
method keywords() in Imdb\MdbBase\Title class doesn't return any data.

**Comment by duck7000** [comment]
Jep you are right, it doesn't work, PR is in progress

**Comment by duck7000** [comment]
PR is done

**Comment by duck7000** [comment]
@jcvignoli can you also test if this fixes the problem?

**Comment by jcvignoli** [comment]
I confirm, it works!

**Comment by duck7000** [comment]
@jcvignoli can you close this issue as it is resolved?
