### ISSUE TITLE
Imdbphp title search doesn't return any result

### ISSUE THREAD

**Issue by jcvignoli** [tboothman/imdbphp#282]
I'm using latest Imdbphp dev revision (d96da50).

Search for titles is broken. Just tried with Fight Club, Barry Lindon, 2001, not a single result is returned.

Imdbphp can still find movies according to their imdb number, though.

**Comment by duck7000** [comment]
There is something strange going on here.
It sometimes works after a few retry's , so the problem lies in fetching the data from imdb i guess
If the search works the fetched data is correct though.

**Comment by duck7000** [comment]
jreklund has added this commit: #c3365fe

**Comment by jcvignoli** [comment]
Correct. Latest commits fixed regression introduced yesterday.
Thanks for letting me know!
