### ISSUE TITLE
Method tagline() in Title class broken

### ISSUE THREAD

**Issue by jcvignoli** [tboothman/imdbphp#283]
Method tagline() in Title class doesn't return any string despite a tagline being available.
Method taglines() works perfectly, though.
Tried with interstellar title.

**Comment by jreklund** [comment]
What imdbphp are you using? It were fixed in 7.3.1.
What php version are you using? We have a php 5.6 compatibility problem in 7.3.1.

**Comment by jcvignoli** [comment]
Sorry for the false positive. Was running an old imdbphp script.
Will update and report back should I find an issue.
Closing this issue in the meantime.
