### ISSUE TITLE
imdb new format "Release info" page

### ISSUE THREAD

**Issue by mam4dali** [tboothman/imdbphp#291]
Hello
Today I noticed some problems that make this library not work properly
After checking, I noticed that a new format can be seen on the release information page
It is different from the previous structure and causes it to not work properly
pic:
![The-Quiet-Girl-2022-Release-info-IMDb](https://user-images.githubusercontent.com/13052531/212221559-289195b8-17cd-4abe-878a-40f635ecdd45.png)

html source:
[html source.txt](https://github.com/tboothman/imdbphp/files/10407548/html.source.txt)

I think we should adjust to the new structure soon

**Comment by jreklund** [comment]
Yeah, they have changed multiple pages to their new format. You can also get the old one sometimes, so they are still rolling them out on all servers. So if you change the code for their new design and re-run the test, you get old one and it fails.

We are either stuck with limited data (what is shown in the picture) or someone need to "crack" how their graphql works, as it's the only way to get the rest of the data. You need to be sending an correct variables and extensions or it will fail, so they do a check for bots.

```
https://caching.graphql.imdb.com/?operationName=TitleReleaseDatesPaginated&variables={data}&extensions={data}
```

```
Content-Type: application/json
```

**Comment by GeorgeFive** [comment]
Just to keep everything in one place, this also affects Companies page.  Same thing.

**Comment by duck7000** [comment]
Eventually all pages links will be converted i guess.
I'm still getting the old pages, even after clearing browser cache

**Comment by Thomasdouscha** [comment]
It cannot get release info.

**Comment by duck7000** [comment]
> We are either stuck with limited data (what is shown in the picture) or someone need to "crack" how their graphql works, as it's the only way to get the rest of the data. You need to be sending an correct variables and extensions or it will fail, so they do a check for bots.

Mm i think you are right, but might there be a solution that activates the all button on that page?
Or somehow get that page after the all button is pressed (by javascript?) I'm thinking out loud here as i have no solution..

**Comment by mam4dali** [comment]
I have spent the last few days testing and reviewing.
These days I can get the information with the following commands
Also, by changing the imdb id in the data, everything works correctly
However, I think this way should be further investigated
I am confused about sha256Hash value


`curl --location -g --request GET "https://caching.graphql.imdb.com/?operationName=TitleAkasPaginated&variables={\"after\":\"\",\"const\":\"tt15576994\",\"first\":200,\"locale\":\"en-US\",\"originalTitleText\":false}&extensions={\"persistedQuery\":{\"sha256Hash\":\"180f0f5df1b03c9ee78b1f410d65928ec22e7aca590e5321fbb6a6c39b802695\",\"version\":1}}" --header "authority: caching.graphql.imdb.com" --header "accept: application/graphql+json, application/json" --header "accept-language: fa,en-US;q=0.9,en;q=0.8" --header "cache-control: no-cache" --header "content-type: application/json" --header "origin: https://www.imdb.com" --header "pragma: no-cache" --header "referer: https://www.imdb.com/" --header "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" --header "x-imdb-client-name: imdb-web-next-localized" --header "x-imdb-user-country: US" --header "x-imdb-user-language: en-US"`

**Comment by tboothman** [comment]
https://www.apollographql.com/docs/apollo-server/performance/apq/

**Comment by duck7000** [comment]
I found this
https://www.imdb.com/interfaces/

It has a archive with aka info but if it is useful as is?

**Comment by duck7000** [comment]
what i find strange is that in my browser (Firefox on Linux) i do get the new pages for a specific movie but if i search with imdbphp the results are mixed, sometimes it works (i presume the old page layout is loaded?) but the second try it doesn't (i presume the new layout?)
Why is this inconsistent? it seems that imdbphp not always loads the same pages (cached pages perhaps?)
I don't use cache in imdbphp (removed it)

**Comment by GeorgeFive** [comment]
Knew it was coming, but I'm no longer receiving any data, at all.  Used to work after a refresh or two, but now, nothing.

**Comment by Thomasdouscha** [comment]
Please someone should fix it.

**Comment by jreklund** [comment]
Here is what I know, somebody can figure out the rest.
- On every `releaseinfo` page there are a .js file named `releaseinfo-{hash}.js`
- That .js file contains a function with the query string `TitleAkasPaginated`
- That query string should somehow result in the sha256 of `180f0f5df1b03c9ee78b1f410d65928ec22e7aca590e5321fbb6a6c39b802695`

```
function y() {
	var n = (0, s.Z)(["\n    query TitleAkasPaginated($const: ID!, $first: Int!, $after: ID) {\n        title(id: $const) {\n            akas(\n                first: $first\n                after: $after\n                sort: { by: COUNTRY, order: ASC }\n            ) {\n                ...AkaItem\n            }\n        }\n    }\n    ", "\n"]);
	return y = function() {
		return n
	}, n
}
```

```
function B(e, t) {
	var n = k(e),
		r = e.context.url;
	if (!n || !t) return r;
	var i = [];
	t.operationName && i.push("operationName=" + encodeURIComponent(t.operationName)), t.query && i.push("query=" + encodeURIComponent(t.query.replace(/#[^\n\r]+/g, " ").trim())), t.variables && i.push("variables=" + encodeURIComponent(N(t.variables))), t.extensions && i.push("extensions=" + encodeURIComponent(N(t.extensions)));
	var o = r + "?" + i.join("&");
	return o.length > 2047 ? (e.context.preferGetMethod = !1, r) : o
}
```

I guess it's just easier to store the sha256 hash instead of downloading this file, parsing it and generate a hash, just to send a cached request. If they change the query the hash will not match anymore anyway.

With all the changes done to Imdb maybe it's time to just close down chop and migrate to Tmdb.

**Comment by duck7000** [comment]
> With all the changes done to Imdb maybe it's time to just close down chop and migrate to Tmdb.

This is something i'm thinking about too, they have a api (free to use, but requires api key) which will provide (not all info like imdb i guess?) information and deliver it fast and reliable.
This project will give a idea, it is build like this library.
https://github.com/kriboogh/TMDB4PHP/

**Comment by GeorgeFive** [comment]
Personally, I'd love to see someone crack this problem and get a fix in so we can continue with IMDb.  I like TMDb, but they don't hold a candle to IMDb in terms of the data that they offer.

**Comment by duck7000** [comment]
> Personally, I'd love to see someone crack this problem and get a fix in so we can continue with IMDb. I like TMDb, but they don't hold a candle to IMDb in terms of the data that they offer.

Well as of also known as i doubt this problem will be cracked at all, unless IMDb will provide full info on that page. the method @jreklund is talking about could be working but relies on a hash key that can change anytime so it is not a reliable option in my view.
Personally i don't care much about aka (in my version I'm planning to convert this to original title only) but if IMDb is going to do the same for all other pages there isn't much hope i guess.

**Comment by jreklund** [comment]
[php-tmdb/api](https://github.com/php-tmdb/api) are the most up to date PHP version I know about and started to look at before I did the last round of fixes to imdbphp. There are some things not present on TMDB and vice versa. I got akas and parental guidance (exklusive) in my application.

The data to find the hash are all there, but I haven't seen the obvious bit where they actual do the computing. GenerateHash are there, but haven't seen the actual conversion. I have tried to pass the whole query into sha256 without luck, so I'm missing some data (or need to remove some).

But If we rely on calculating sha256 we need to grab those queries every time to have a valid hash. Or store them statically.

First we do a normal query to the website (or Graph?) and later on multiple queries to get all extra data so lot of re-writes need to happen.

We could go with limited data approach like #292 but I would remove that method from my application instead. All or nothing.

**Comment by tboothman** [comment]
It's a bit tedious to explore the schema it's very possible to get this data from the graphql api
Here's the schema for the Title object:
![image](https://user-images.githubusercontent.com/1813336/216784192-784de3d2-63f8-4c37-abaf-6bb3661ed34e.png)
Results of fetching the releasedates:
![image](https://user-images.githubusercontent.com/1813336/216784082-e3eb1a63-4686-400e-918c-569378b8dee7.png)
Here's the query to fetch information about a GraphQL type:
```language=graphql
query Type($type: String!) {
  __type(name: $type) {
    ...FullType
  }
}

fragment FullType on __Type {
      kind
      name
      description
      
      fields(includeDeprecated: true) {
        name
        description
        args {
          ...InputValue
        }
        type {
          ...TypeRef
        }
        isDeprecated
        deprecationReason
      }
      inputFields {
        ...InputValue
      }
      interfaces {
        ...TypeRef
      }
      enumValues(includeDeprecated: true) {
        name
        description
        isDeprecated
        deprecationReason
      }
      possibleTypes {
        ...TypeRef
      }
    }

    fragment InputValue on __InputValue {
      name
      description
      type { ...TypeRef }
      defaultValue
      
      
    }

    fragment TypeRef on __Type {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                  ofType {
                    kind
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
```
Query to fetch the releaseDates:
```
{
  title(id:"tt0120737") {
    releaseDates(first: 9999) {
      edges {
        node {
          country {
            id
            text
          }
          day
          month
          year
          attributes {
            id
            text
          }
        }
      }
		}
  }
}
```

**Comment by tboothman** [comment]
Imdb have blocked the __schema {} request that lets you fetch everything about the endpoint and makes the documentation and query helpers work for graphqli.
I'm going to see if I can make an endpoint that'll let you get the full schema so graphqli can help you type out queries. It's pretty slow work fetching the schema for each subobject and typing out the query without any editor support.

**Comment by duck7000** [comment]
@tboothman 
Pardon my ignorance (and you will probably ignore me) but that api has no public entrance so how can you get any data from it? 
Are you using your personal account to figure this out?
for any user of this library this is important to know so i don't ask this for myself.

**Comment by tboothman** [comment]
It is a public api. It's what the frontend of the website is using to fetch data to render the page.
For example, if you go to https://www.imdb.com/title/tt0120737/releaseinfo and press '50 more' under release date it does a graphql query to fetch some more data (which is where I saw the response shape and guessed the request shape for the query I put above)

**Comment by tboothman** [comment]
I've made a proxy that makes graphiql work locally so you can browse around the imdb API. It's pretty incredible how many types they've got (~1000). I imagine you can fetch a good portion of all the data from there now.

https://github.com/tboothman/imdbphp/commit/4b906af775232f91a1882393a8af6ae3a282c1e1

1. Get Graphiql (the chrome extension is nice) https://chrome.google.com/webstore/detail/graphiql-extension/jhbedfdjpmemmbghfecnaeeiokonjclb?hl=en
2. go into the graphql folder
3. composer install (get composer if you haven't https://getcomposer.org/download/)
4. php -S localhost:5000
5. Go to http://localhost:5000 in the graphiql extension
6. Have a look in the docs and see what's possible. Try the query I've put in here and see what else you can find

**Comment by tboothman** [comment]
Wrote a bit of code to get releaseInfo using graphql. Wrote it by just putting a big string for the query in the code, which works fine but basically relies on your writing the query out using graphiql.
https://github.com/tboothman/imdbphp/blob/graphql/src/Imdb/Title.php#L2591
Also tried out a library that will build a load of classes for you so you can 'safely' query the schema because it knows about all the objects available. It works well enough but it's a bit verbose and harder to read than the raw graphql query:
https://github.com/tboothman/imdbphp/blob/graphql/graphql/q.php#L15

**Comment by tboothman** [comment]
Bit of a grind but nearly there. Still two methods to fix but i'm not particularly inclined to look at soundtracks and i'm not entirely sure what the results of the methods that use parse_extcontent was.
https://github.com/tboothman/imdbphp/pull/293

**Comment by duck7000** [comment]
@tboothman 
Well i think that the users here will appreciate all your work, it looks impressive!
But it will make this library more complicated and harder to understand in my view.
And is it still necessary to install a graphiQL browser extension?  if so than this will be one more dependency for this library
Just my thoughts though

**Comment by tboothman** [comment]
Can't say that I agree.
There's no new dependencies other than a [new class to do graphql requests](https://github.com/tboothman/imdbphp/pull/293/files#diff-fcfe3437e50c81326e7b5ecd820988bb9fc2632e0b5777c97362443a53da906a) and cache them to disk.

Calling a graphqlapi is so much simpler than parsing html.
Take https://github.com/tboothman/imdbphp/pull/293/commits/e36653feb84c9a2b5dedcafde4a4ffc52d62f558#diff-2a4bb245c110c1fe94bfeb5c0ae91d4435d947b30473ad5acabd1366a77b1776L578 for example. movie_recommendations was an indecipherable series of xpath queries and regexes, now it's a some nested field names and a loop to turn it into the right results shape.

**Comment by jreklund** [comment]
Wow - that's quite a change in the amount of code that gets cleaned up. Need to read up on GraphQL some day, as I have never used it before.

**Comment by tboothman** [comment]
https://github.com/tboothman/imdbphp/releases/tag/v8.0.0

**Comment by duck7000** [comment]
> I've made a proxy that makes graphiql work locally so you can browse around the imdb API. It's pretty incredible how many types they've got (~1000). I imagine you can fetch a good portion of all the data from there now.
> 
> [4b906af](https://github.com/tboothman/imdbphp/commit/4b906af775232f91a1882393a8af6ae3a282c1e1)
> 
>     1. Get GraphiQL (the chrome extension is nice) https://chrome.google.com/webstore/detail/graphiql-extension/jhbedfdjpmemmbghfecnaeeiokonjclb?hl=en
> 
>     2. Checkout the graphql branch and go into the graphql folder
> 
>     3. composer install (get composer if you haven't https://getcomposer.org/download/)
> 
>     4. php -S localhost:5000
> 
>     5. Go to http://localhost:5000 in the GraphiQL extension
> 
>     6. Have a look in the docs and see what's possible. Try the query I've put in here and see what else you can find

I can't get this to work, graphiql extension is not even loaded (not available in developer tools) vendor/autoload.php not found, guzzle http client not found etc

Can you give better instructions or a simple way to display a schema of a movie?
