### ISSUE TITLE
Install issue imdbphp 8.0

### ISSUE THREAD

**Issue by Thomasdouscha** [tboothman/imdbphp#294]
"Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for coderjerk/bird-elephant ^0.6.1 -> satisfiable by coderjerk/bird-elephant[v0.6.1].
    - coderjerk/bird-elephant v0.6.1 requires guzzlehttp/oauth-subscriber ^0.6.0 -> satisfiable by guzzlehttp/oauth-subscriber[0.6.0].
    - Conclusion: don't install guzzlehttp/guzzle 7.0.0
    - guzzlehttp/oauth-subscriber 0.6.0 requires guzzlehttp/guzzle ^6.5|^7.2 -> satisfiable by guzzlehttp/guzzle[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.6, 6.5.7, 6.5.8, 7.2.0, 7.3.0, 7.4.0, 7.4.1, 7.4.2, 7.4.3, 7.4.4, 7.4.5, 7.5.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.6, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.7, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.8, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.3.0, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.4.0, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.4.1, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.4.2, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.4.3, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.4.4, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.4.5, 7.0.0].
    - Can only install one of: guzzlehttp/guzzle[7.5.0, 7.0.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.0) -> satisfiable by guzzlehttp/guzzle[7.0.0].

Installation failed, reverting ./composer.json to its original content.
"

**Comment by Thomasdouscha** [comment]
This is first time i had issue when i install imdbphp. I cannot use it

**Comment by tboothman** [comment]
What is this from? The only dependencies of imdbphp are psr/log and psr/simple-cache

**Comment by Thomasdouscha** [comment]
composer update imdbphp/imdbphp created error as i mentioned.
But get zip and open it. It works with this way. There is no issue 

My website's framework is laravel 5.6. May be when i update imdbphp thatswhy i had this issue. But till today i did not have any issue like this

**Comment by Thomasdouscha** [comment]
![image](https://user-images.githubusercontent.com/43930732/218605034-9b3ff36b-1f09-4046-9cf8-7d0ed20361b5.png)
I created this movie card now. It seems that works perfect very well!

**Comment by Thomasdouscha** [comment]
I should check it some days. Than i will make a comment if there is any issue.

**Comment by tboothman** [comment]
Just to be super clear though, this library doesn't use guzzle and has no dependency on it.

I made a project with nothing but imdbphp and this is what it installed.
![image](https://user-images.githubusercontent.com/1813336/218605519-b4ce6737-c1c7-4d8c-aaaa-d1ef2d0c898e.png)

It looks like you've got guzzle locked at 7.0.0 in your composer.json but something else wants a different version. Best to avoid explicit versions if you can and use ^7.whatever so the dependencies can haggle over the version they want to use.

**Comment by Thomasdouscha** [comment]
Yes you are right. It is up to my laravel framework. 

my first comment it is faster than past when update or open new movie card.

**Comment by Thomasdouscha** [comment]
![image](https://user-images.githubusercontent.com/43930732/218607375-af1c1d21-ee11-4d64-85fc-8cc39d7231d6.png)

As you mentioned some data has been changed thatswhy my code has some issue. I should revise it.

**Comment by tboothman** [comment]
Nope that's a bug. I wrongly assumed that every aka had a country

**Comment by tboothman** [comment]
Fixed https://github.com/tboothman/imdbphp/commit/e72f450f6d07993194ef19ba4d7a14cd06938346

**Comment by Thomasdouscha** [comment]
I will test again
