### ISSUE TITLE
method photo_localurl() doesn't return thumbnail pictures if set to true

### ISSUE THREAD

**Issue by jcvignoli** [tboothman/imdbphp#295]
Using imdbphp 8.0.1

I used to use `photo_localurl()` set to true ( `photo_localurl( true )` ) to return thumbnail pictures.

I read the last readmes and could find any mention of changes to the method. If set to false, it properly returns the "non-thumbnail" picture.

Thanks!

**Comment by tboothman** [comment]
Going to need some more information. There's tests for thumbnails that pass and the tests and code around this hasn't changed for years

**Comment by jcvignoli** [comment]
I haven't been able to reproduce the issue today. Guess was either IMDb pictures that were down yesterday when I tried, or a faulty internet connection, I don't get it.
Should I face the issue again, I will reopen the ticket.
