### ISSUE TITLE
Cache filesize is too big

### ISSUE THREAD

**Issue by Thomasdouscha** [tboothman/imdbphp#304]
Hi,
Cache filesize is too big. Approximately 1 mb for title. It was not like this. Is there any solution about it?

![image](https://user-images.githubusercontent.com/43930732/235909905-e49e94ff-35ea-4ddb-b222-ae2ef5810694.png)

**Comment by duck7000** [comment]
Only thing i can think of is did you enable zip compression in config?

**Comment by Thomasdouscha** [comment]
I did but it was not useful. I cannot understand why cache filesize is so
big?

duck7000 ***@***.***>, 3 May 2023 Çar, 16:55 tarihinde şunu
yazdı:
