### ISSUE TITLE
Sharing methods that are converted to GraphQL

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#314]
@all

I have successfully converted methods to GraphQL:
Locations
Soundtrack
Quotes
Trivia (including spoiler check)
Genres
Rating
Aka (added original title to aka query, no need for extra method)
Title_year
Metacritic
Plotoutline
Country
Language
Mpaa
Top250
Episodes (byYear is now working)
Director
Writer
Composer
Producer
Votes
isOngoing (new: used to get if TV Series is still going or ended)
gross
budget

New method principalCredits (it will fetch Director, Writer, Creator and Cast from top title page if available) This replaces Creator() and headStars()

They are all in my GitHub repo https://github.com/duck7000/imdbphp6 (check the commits)

Feel free to use them here in imdbphp but remember that my version differs from this version so you can't copy the methods directly. Adjustments are needed. They are basically the same but might fetch more data or in different format.
Or you could use my version, most methods are there and even person and personSearch is in it.

I have no more interest in making pull requests for those methods, let's say there is a reason that i use my own version.

This way i can still contribute to this version, i hope that somebody will pick this up further so everybody can benefit from it.

Edit: @tboothman I was skeptical to the move to GraphQL but i have to fully admit that it is actually much easier is to work with.
That is.. after you figure out how it works... Thanks for your groundwork about GraphQL.!

**Comment by jcvignoli** [comment]
Hi @duck7000,
Since I use Person class, I will stick to the tboothman version, but thanks for the idea!

**Comment by duck7000** [comment]
Sure i understand that but maybe you can use my work to convert the person class (or title class methods) and create PR? 
I'm probably not going to do that as I'm not using the person class myself but it will benefit a lot of users here.

**Comment by duck7000** [comment]
I have converted the mainsearch to GraphQL and i'm sharing it here, and no i'm not going to make a PR
Remember that it is different then the mainsearch here but it will give you a good idea how it works.

I hope that someone will pick this up and make a PR...

```
    public function search($searchTerms)
    {
        $results = array();
        $query = <<<EOF
query Search {
  mainSearch(first: 10, options: {searchTerm: "$searchTerms", type: TITLE, includeAdult: true}) {
    edges {
      node {
        entity {
          ... on Title {
            id
            titleText {
              text
            }
            titleType {
              text
            }
            releaseYear {
              year
              endYear
            }
          }
        }
      }
    }
  }
}
EOF;
        $data = $this->graphql->query($query, "Search", ["id" => "tt$this->imdbID"]);
        foreach ($data->mainSearch->edges as $key => $edge) {
            $imdbId = isset($edge->node->entity->id) ? str_replace('tt', '', $edge->node->entity->id) : '';
            $title = isset($edge->node->entity->titleText->text) ? $edge->node->entity->titleText->text : '';
            $movietype = isset($edge->node->entity->titleType->text) ? $edge->node->entity->titleType->text : '';
            $yearRange = '';
            if (isset($edge->node->entity->releaseYear->year)) {
                $yearRange .= $edge->node->entity->releaseYear->year;
                if (isset($edge->node->entity->releaseYear->endYear)) {
                    $yearRange .= '-' . $edge->node->entity->releaseYear->endYear;
                }
            }
            $results[] = array(
                'imdbid' => $imdbId,
                'title' => $title,
                'year' => $yearRange,
                'movietype' => $movietype
            );
        }
        return $results;
    }
```

**Comment by duck7000** [comment]
I'm working on person class.
And person search is already added back

**Comment by jcvignoli** [comment]
@duck7000 Thanks for the effort! But your version is not yet ready for my use, actually. I overwrited Boothman's classes with yours, and there are actually missing methods (I briefly saw photo_url() for example) which prevented me to go further.
I will have to take a look in depth at a later stage, since it's seems that Boothman is more or less stoping the development.
Cheers and thanks for your work!

**Comment by duck7000** [comment]
Well i stripped everything that i didn't need so yes there are things missing.

Can you give a list off missing methods that you actually need to use?

I might consider to re add them although i probably not going to use it myself.
I don't use the person class myself but i discussed it with @georgefive and re added.

**Comment by jcvignoli** [comment]
Hey @duck7000 
I'm not certain to fully understand the two edits: do you mean that I should copy Boothman's photo_local() method into your class?
It'd be a bad idea for my use. In terms of maintainability it'd be soon a nightmare (I develop a wordpress plugin based on imdbphp classes), there are many other methods that I should copy at every new release ( photo_local() depends on savephoto(), ie).

**Comment by duck7000** [comment]
> I'm not certain to fully understand the two edits: do you mean that I should copy Boothman's photo_local() method into your class?

Yes that is what i meant, but i understand your concerns.
Maybe my version is not quite suitable for your needs so feel free to use whatever you want.
But the tbootman version has sever problems at the moment so you have to fix that yourself as i don't expect fixes from tboothman soon

Do you use every method that is in title class? then my version is not for you i guess, it is stripped down to bare minimum for my needs

And the second edit, mixing classes is in this case not a good idea, either use my version or tboothman version.

I might possible consider maintaining 2 versions, a stripped down version and a full version but i don't know if that will ever happen

**Comment by jcvignoli** [comment]
Thanks for the clarification.
I use most of the methods in Title and Person.
Will wait to see if have the time and willingness to expand your version, since seems that GraphQL is the new way to go :)

**Comment by duck7000** [comment]
Re open this, maybe somebody still has interest to use it for imdbphp
