### ISSUE TITLE
Error if cache folder is not created

### ISSUE THREAD

**Issue by DonBananos** [tboothman/imdbphp#32]
If the cache folder is not in the directory, the application crashed. 
therefore, i've added this little piece of code to the project where i'm using your great work.
````
/*
 * Check if the cache folder exists in the imdbphp api.
 * if it doesn't - then create it!
 */
if (!file_exists('../includes/api/imdbphp/cache'))
{
	mkdir('../includes/api/imdbphp/cache', 0777, true);
}
````

Anyway, Thanks for sharing this!

**Comment by IzzySoft** [comment]
Sound good so far – but it shouldn't use a hard-coded path. There's a config variable `cachedir` which should be used instead. Furthermore, this check is only required when caching is enabled (config: `usecache`). And even then, it should not be done "too often". A quick idea might be doing so in the constructor; but this I better leave to @tboothman as he's more familiar with the current code :innocent:

**Comment by DonBananos** [comment]
This was just my quickfix. But of course for a sustainable solution, config
file is the way to go. A chef on whether or not the cache is enabled is
likewise the better choice. Well, all your points are valid. Thank you sir.

tor. 4. jun. 2015 16.14 skrev Izzy <notifications@github.com>:
