### ISSUE TITLE
Is searching by type broken?

### ISSUE THREAD

**Issue by Fossil01** [tboothman/imdbphp#325]
I get all kinds of podcasts etc as results too while using 

```php
$imdb->search('Blabla', [TitleSearch::MOVIE])
```

For example this one: https://www.imdb.com/title/tt23547604/ which shows as a "Podcast Episode" but comes back with `#main_movietype: "Movie"`

Also had this one just popup: https://www.imdb.com/title/tt28856207/ another podcast.

**Comment by duck7000** [comment]
There is a lot more broken with imdphp so good luck with this PR..

I don't think that tboothman has any more interest in this project

**Comment by duck7000** [comment]
Well.. you are in luck that @jreklund merged your request but it still feels like flogging a dead horse to me
