### ISSUE TITLE
"Undefined variable" error in function get_gross

### ISSUE THREAD

**Issue by dr-brown** [tboothman/imdbphp#39]
Hello,

if no date is specified for the Gross value on the "Box office / business" page
the function `get_gross` from title.php generates a "Undefined variable" error
for `$dateValue`.

**Comment by tboothman** [comment]
Can you give an example of a film that does this?

**Comment by IzzySoft** [comment]
I guess that's due to three `if` conditions missing their `else` counterparts. Adding a simple `$dateValue = NULL;` (i.e. "declaring a default for fallback") before line 2410 should solve that.

**Comment by dr-brown** [comment]
Example: http://www.imdb.com/title/tt0056592

**Comment by tboothman** [comment]
A null probably seems like the best solution in this case. To kill a mockingbird had a year .. but there was only one gross so it didn't really matter. Goldfinger http://www.imdb.com/title/tt0058150/business has no year at all so no date needs to be accounted for.

**Comment by tboothman** [comment]
While I'm in here should I unformat the 'value' into a currency symbol and amount? If I were using it I think I'd want that .. but I'm not the one using it

**Comment by dr-brown** [comment]
I don't need a separation between symbol and amount.
