### ISSUE TITLE
original title always blank

### ISSUE THREAD

**Issue by nmpgaspar** [tboothman/imdbphp#42]
it seems that original title is always returning an empty reply. As an example: http://www.imdb.com/title/tt2938956/ 

Also note this somehow related: setting $config->language = 'en-US'; does not seem to force akas.imdb to return the titles as if the request came from the US..

**Comment by nmpgaspar** [comment]
sorry, just pulled latest and it works :)

**Comment by tboothman** [comment]
You should give https://sibbell.com a go, it can send you an email when a new package is released

**Comment by IzzySoft** [comment]
@tboothman or just subscribe the project at Github here. Also gives you notification by mail on new releases (and more) – plus upvotes the project :smiley_cat:
