### ISSUE TITLE
episodes() does not handle 'Unknown' seasons

### ISSUE THREAD

**Issue by nmpgaspar** [tboothman/imdbphp#43]
It seems that the episodes() function does not take into account the seasons labelled as 'unknown'. Here's an example: http://www.imdb.com/title/tt4508902

I can only see the 12 episodes from season 1, but nothing from the Unknown season..

**Comment by duck7000** [comment]
Personally i find this a flaw in the imdb site of this movie.
I never heard of a series that has 1 season and a unknown something.
