### ISSUE TITLE
imdb:photo problem

### ISSUE THREAD

**Issue by alexidoia** [tboothman/imdbphp#47]
release 2-2.6.1
function photo never return url for big cover.

**Comment by tboothman** [comment]
That's 8 months old, you want 3.2.0

**Comment by alexidoia** [comment]
I don't understand, I can't find it, on the izzy site, I downloaded the latest imdbphp2 release.
http://projects.izzysoft.de/trac/imdbphp/wiki/Download

**Comment by alexidoia** [comment]
I realized that everything has changed since the v3.
I used to integrate the lib into a wordpress plugin buy including the imdb.class and starting from there. This file does not seem to exist anymore. I'll have to change my integration code. I don't know where to start really.
thanks

**Comment by IzzySoft** [comment]
I should really update that download page and include a pointer (will do so now). Sorry for the confusion, @alexidoia – but that page has, as it says, IMDBPHP2 (i.e. v2.x). Tom took over meanwhile, and continued development. v3.x has a lot of its structure changed, and is available for download [here](https://github.com/tboothman/imdbphp/releases).

**Comment by tboothman** [comment]
Have a look at the release notes for 3.0 - it's a fairly straight forward change
https://github.com/tboothman/imdbphp/releases/tag/v3.0.0
