### ISSUE TITLE
Title movie english

### ISSUE THREAD

**Issue by Alexisback** [tboothman/imdbphp#50]
how to configure this code to save the titles in English
I live in Russia, and these tiles are saved in "Russian language"
thank you

` /**
   * IMDB server to use.
   * choices are www.imdb.&lt;lang&gt; with &lt;lang&gt; being one of
   * de|es|fr|it|pt, uk.imdb.com, and akas.imdb.com - the localized ones are
   * only qualified to find the movies IMDB ID (with the imdbsearch class;
   * akas.imdb.com will be the best place to search as it has all AKAs) -- but
   * parsing (with the imdb class) for most of the details will fail for
   * most of the details.
   * @var string imdbsite
   */
  public $imdbsite = "akas.imdb.com";

  /**
   * Tell IMDB which is the preferred language.
   * Any valid language code can be used here (e.g. en-US, de, pt-BR).
   * If this option is specified, the Accept-Language header with this value
   * will be included in the requests.
   * @var string
   */
  public $language = "en-US";`

**Comment by tboothman** [comment]
What results do you get with that configutation?
I tried changing my accept-language header to en-US and I got the american title and pt-BR for the portuguese one.
It's possible that $imdbsite has to be "www.imdb.com". I'm not entirely sure what the benefit/difference is for using akas although it seems to do the same for me as www

**Comment by Alexisback** [comment]
Hi tboothman

the "configuration" and the one above
I rebooted the server (localhost) and now scrape and English
I hope it works

ps: you read the post about the actors filmography?

thanks

**Comment by tboothman** [comment]
Ah right, so you cached the russian pages?

**Comment by Alexisback** [comment]
now work correct in english

**Comment by Alexisback** [comment]
re-open this topic
something does not work in the "person" script
(I set the configuration as in the screenshot)
When download the filmography film does not all titles are in English
some films are in Russian language
I wish them all with the original title in English
precise that I live in russia

![ss screen capture 069](https://cloud.githubusercontent.com/assets/18039740/14100764/7cd759c8-f598-11e5-83fa-7d4a1377ebc3.png)
![ss screen capture 070](https://cloud.githubusercontent.com/assets/18039740/14100767/7cd96f88-f598-11e5-8216-dd63c53bfccb.png)
![ss screen capture 071](https://cloud.githubusercontent.com/assets/18039740/14100768/7cdcafa4-f598-11e5-8025-f6a4164a8bc2.png)
![ss screen capture 072](https://cloud.githubusercontent.com/assets/18039740/14100765/7cd884ba-f598-11e5-87e9-0f9b9488e094.png)
![ss screen capture 073](https://cloud.githubusercontent.com/assets/18039740/14100766/7cd8e91e-f598-11e5-9b94-a2b605bb9a36.png)
