### ISSUE TITLE
Title movie in english (2) re-open

### ISSUE THREAD

**Issue by Alexisback** [tboothman/imdbphp#52]
re-open this topic
something does not work in the "person" script
(I set the configuration as in the screenshot)
When download the filmography film does not all titles are in English
some films are in Russian language
I wish them all with the original title in English
precise that I live in russia

![ss screen capture 069](https://cloud.githubusercontent.com/assets/18039740/14100764/7cd759c8-f598-11e5-83fa-7d4a1377ebc3.png)
![ss screen capture 070](https://cloud.githubusercontent.com/assets/18039740/14100767/7cd96f88-f598-11e5-8216-dd63c53bfccb.png)
![ss screen capture 071](https://cloud.githubusercontent.com/assets/18039740/14100768/7cdcafa4-f598-11e5-8025-f6a4164a8bc2.png)
![ss screen capture 072](https://cloud.githubusercontent.com/assets/18039740/14100765/7cd884ba-f598-11e5-87e9-0f9b9488e094.png)
![ss screen capture 073](https://cloud.githubusercontent.com/assets/18039740/14100766/7cd8e91e-f598-11e5-9b94-a2b605bb9a36.png)

**Comment by tboothman** [comment]
I don't know what to say really. When I go to imdb, even with tor, i get the english version becauase my browser's sending `Accept-Language: en-GB,en;q=0.5`. If i change the accept-language header i get a different language .. there doesn't seem to be any magic to it and it seems very consistent. Oddly if I send `Accept-Lanauge: ru" I don't get russian. Portugeuse, american and german work fine though.

**Comment by Alexisback** [comment]
I'm doing a test with a VPN and IP of Japan
the settings are these

```
public $imdbsite = "akas.imdb.com";

public $language = "en-US";
```
result:
all titles are in English

when I connect without VPN, they are loaded titles in English and Russian (my ip resides in russia)

I do not understand
![ss screen capture 075](https://cloud.githubusercontent.com/assets/18039740/14155365/1c5cd31a-f6ca-11e5-8499-c1b1a81ba203.png)

**Comment by Alexisback** [comment]
I'm doing a test with a VPN and IP of United States
the settings are these

```
public $imdbsite = "akas.imdb.com";

public $language = "en-US";
```
result:
all titles are in English

when I connect without VPN, they are loaded titles in English and Russian (my ip resides in russia)

I do not understand
![ss screen capture 076](https://cloud.githubusercontent.com/assets/18039740/14155664/5cbf806e-f6cb-11e5-9d9e-15e6e5376e22.png)

**Comment by Gavo34** [comment]
Just a thought to the OP.

After changing language in settings did you clear the cache files for movies with wrong title?


Thanks for keeping this script updated, I have used it since V1 :)

**Comment by Alexisback** [comment]
yes, I deleted the files
I downloaded but there are titles in English and Russian
