### ISSUE TITLE
Add ability to replace cache

### ISSUE THREAD

**Issue by yyanavichus** [tboothman/imdbphp#57]
1) I have checked out briefly PSR-6 cache interfaces and they seem over-complicated. Can we have our simple interface instead? Something like that:

```php
interface CacheInterface
{
    public function get($key);

    public function set($key, $value);
}
```

2) Can we use dependency injection container both for cache and logger?
Right now we have method `setLogger`, maybe we can have similar method `setCache` as well?
The only drawback in this case is that we have to code the following steps: a) set log for `MdbBase` (i.e. `Title`), b) set log for cache c) set cache for `Title`.
When using dependency injection container we have to set dependency only once, and we can have, for example, 2 additional config variables: `cachetype` and `logtype` which are class names for cache and logger

I can work on that points and make a pull request soon

**Comment by tboothman** [comment]
I agree about not using PSR-6 - it's over complicated and the current cache can't support its interface as it doesn't have expiry times per key.

If you don't mind a custom interface then that works for me.

Where are you planning on storing your cache if not in a file? If it's useful enough that someone else would use it it might be worth putting it in as an optional cache as well as an interface so anyone can make any cache they like.

**Comment by yyanavichus** [comment]
1) We have to use database cache, because an application has to be running on the cloud.

2) So, you would prefer having a `setCache` method rather than using dependency injection? As I understand you do not want to make huge changes to the code which is working for many years and I can agree with you.

**Comment by tboothman** [comment]
I don't have a particularly strong opinion on how the dependency injection should work. I went with the setLogger as that's what PSR-3 seemed to be implying was a good way to go.

Just reading the code I don't think the setLogger thing will even work properly. If you set the logger after the cache/pages class are created their logger won't be changed.
Perhaps setting the dependencies in the constructor is the way to go then.

**Comment by yyanavichus** [comment]
> Just reading the code I don't think the setLogger thing will even work properly. If you set the logger after the cache/pages class are created their logger won't be changed.

I had the same thoughts, `MdbBase` constructor uses default logger before we can change it via `setLogger` method
