### ISSUE TITLE
Limit array 

### ISSUE THREAD

**Issue by joeymetal** [tboothman/imdbphp#62]
Hello how can I limit in a search for the movie or series
the number of directors and actors
, $ Imdb-> director (), $ imdb-> cast ()
pq returns a very large list of names

**Comment by tboothman** [comment]
array_slice ? I don't know what you're asking or even what methods you're talking about to be honest

**Comment by joeymetal** [comment]
I do not know much php just wanted what was the function because was not finding
but it has to get the trailer too?
if that and the name?
