### ISSUE TITLE
imdb seems to have broken posters they were showing 2 days ago

### ISSUE THREAD

**Issue by flier56** [tboothman/imdbphp#65]

**Comment by DeNeDe** [comment]
have the same issue. anything is displayed, except posters and languages or main language of the movie/show

**Comment by redradler** [comment]
Same issue here. Language and country are missing.

**Comment by DeNeDe** [comment]
on the latest 2 commits country started to work but on languages after using the update i get printed Array

**Comment by IzzySoft** [comment]
@DeNeDe Countries is issue #64 which Tom just fixed :)

**Comment by DeNeDe** [comment]
i know. had error in my page code. all works now except the poster

**Comment by tboothman** [comment]
They're serving the images on https now which this can't deal with. Everything's working fine except for the image downloading now, as far as I can tell

**Comment by tboothman** [comment]
All the tests pass and the demo page looks ok to me. Raise another ticket if you see anything else.

**Comment by tboothman** [comment]
You guys were pretty hot off the mark on this, I run the tests at 7pm every day, so you beat it by 5 hours. I imagine imdb did a fairly late release yesterday after I ran the tests last.

I'm not sure this fix is going to work for everyone. If you've not got the https stream wrapper built into php it'll fail pretty hard. I would hope everyone has that .... I'm fairly sure it's in php by default, but you could compile it without.
Now we're doing SSL it's going to require libssl somewhere .. either in php or in the curl extension for php. Feel free to open this back up if you're having any problems.

**Comment by flier56** [comment]
posters  working here now
Thanks

**Comment by DeNeDe** [comment]
thanks

**Comment by jreklund** [comment]
Hi, my hosting provider have allow_url_fopen=0 by default and you're not allowed to change it. So the only way to access https links is with cURL on my host.

> if(function_exists('curl_version')) {
> 	$ch = curl_init();
> 	curl_setopt($ch, CURLOPT_URL, $photo_url);
> 	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
> 	$image = curl_exec($ch);
> 	curl_close($ch);
> } else {
> 	$image = @file_get_contents($photo_url);
> }
