### ISSUE TITLE
retrieving pics

### ISSUE THREAD

**Issue by wunderkinnd** [tboothman/imdbphp#69]
Searched the doku, but found nothing helpful:

Is the movieposterdb-api still in developement? It is not working properly on my system.
Is it possible to extract the movie-posters from imdb?

Thanks

**Comment by tboothman** [comment]
I've never actually used that but it went down at one point, then it came back with almost no content. Nobody's ever complained that it didn't work so I forgot about it.
Looks like the site works slightly differently now .. but it seems it'd be pretty simple to fix though as the posters come back as json from http://www.movieposterdb.com/json/Movie/mid=133093
Looks like you a reasonably large one without signing in, but it might be a bit more complicated to get the larger ones.
I personally just use ``Title::photo(true)``` to get the image url then modify it to get the size I want .. but ``Title::photo(false)``` will strip off the resizing and get you an image that is as large as the original image imdb has.

**Comment by tboothman** [comment]
Are you fine with using the imdb posters? I could probably have a go at fixing the movie poster db code, but it probably shouldn't be in this project at all .. so I'll just delete it if you're not interested as nobody else seems to be.
