### ISSUE TITLE
Language and Country missing

### ISSUE THREAD

**Issue by redradler** [tboothman/imdbphp#73]
Hello,

since Thursday I can't retrieve the country of production and the original language of the movies.
Has anyone the same issue?

Keep up the good work and thank you!

Christian

**Comment by jreklund** [comment]
src\Imdb\Title.php
Line 573:
`if (preg_match_all('!href="/search/title\?.+?primary_language=([^&]*?).+?"[^>]*>\s*(.*?)\s*</a>(\s+\((.*?)\)|)!m',$this->page["Title"],$matches)) {`
Line 1007:
`if (preg_match_all('!/search/title\?country_of_origin=.+?\s.+?>(.*?)<!m',$this->page["Title"],$matches))`

**Comment by tboothman** [comment]
Thanks guys, this is sorted now

**Comment by redradler** [comment]
Thank you very much!
