### ISSUE TITLE
Made some new methods and altered a few others, May intrest

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#75]
Hi
I have made some modifications to existing methods as well altered a few others.
Maybe this is of intrest to merge with imdbphp2?
they are written in the old style (before tboothman took over) so you have to rewrite some it.

I made a method to get the metascore (Metacritics) from the imdb website. It returns the integer value or integer 0 if not found
  
```
public function metacritics() {
		if ($this->page["Title"] == "") $this->openpage ("Title");
		if ( $this->page["Title"] == "cannot open page" ) return $this->metacritics = 0; // no such page
		if ( preg_match_all('!<div class="metacriticScore score_favorable titleReviewBarSubItem">\s*(.*?)\s*</div>!ims', $this->page["Title"], $matches) ) {
			return $this->metacritics = trim(strip_tags($matches[1][0]));
		}
		else{
			return $this->metacritics = 0;
		}
	}
```

I altered the method recommendations.
I found out that there is another way to find recommendations but they are different than the ones on the title page. These are possibly based on user ratings i gues. I made it as a alternative so that if not found on the title page it will get the other ones.
Maybe splitting in 2 different methods is even beter?

```
public function movie_recommendations() {
		if ( empty($this->movierecommendations) ) {
			if ($this->page["Title"] == "") $this->openpage ("Title");
			if ( $this->page["Title"] == "cannot open page" ) return $this->movierecommendations; // no such page
			if ( preg_match_all('!<div class="rec-title">\s*(.*?)\s*</div>!ims', $this->page["Title"], $matches) ) {
				for ($i=0;$i<count($matches[0]);++$i){
					if (preg_match('!<a\s+href="/title/tt(\d{7})/[^>]*>\s*(.+)\s*</a>!ims',$matches[0][$i],$match)){
						if (preg_match('!<span class="nobr">\s*(.*?)\s*</span>!ims',$matches[0][$i],$year)){
							$this->movierecommendations[] = array('title'=>strip_tags($match[2]),'imdbid'=>$match[1],'year'=>strip_tags($year[0]));
						}
						else{
							$this->movierecommendations[] = array('title'=>strip_tags($match[2]),'imdbid'=>$match[1],'year'=>'');
						}
					}
					else{
						return $this->movierecommendations;
					}
				}
			}
			else{
				if ($this->page["Recommendations"] == "") $this->openpage ("Recommendations");
				if ( $this->page["Recommendations"] == "cannot open page" ) return $this->movierecommendations; // no such page
				if ( preg_match_all('!<td valign="middle"><font.*?>\s*(.*?)\s*</font></td>!ims', $this->page["Recommendations"], $matches) ) {
					foreach ($matches[1] as $value){
						if (preg_match('!<a\s+href="/title/tt(\d{7})/[^>]*>\s*(.+)\s*</a>!ims',$value, $match)){
							if (preg_match('/\(.*?\)/', $value, $year)){
								$this->movierecommendations[] = array('title'=>strip_tags($match[2]),'imdbid'=>$match[1],'year'=>$year[0]);
							}
							else{
								$this->movierecommendations[] = array('title'=>strip_tags($match[2]),'imdbid'=>$match[1],'year'=>'');
							}
						}
						else{
							return $this->movierecommendations;
						}
					}
				}
				else{
					return $this->movierecommendations;
				}
			}
		}
	return $this->movierecommendations;
	}
```

I made a method to show the imdb picture. If you direct link the picture it won't work (at least not by me) But if you save the picture in a variable it will work. i added it in the photo section.
You can show the picture like this `<img src="data:image/jpeg;base64,{$movie->showPhoto()}">`

```
public function showPhoto($thumb = true) {
    $photo_url = $this->photo($thumb);
    if (!$photo_url) {
      return false;
    }
	$imageData = @file_get_contents($photo_url);
	return base64_encode($imageData);
  }
```

The method locations doesn't work so i made something that does

```
public function locations() {
    if ( empty($this->locations) ) {
      if ( empty($this->page['Locations']) ) $this->openpage("Locations");
      if ( $this->page['Locations'] == "cannot open page" ) return array(); // no such page
      if ( preg_match_all('!<dt>(<a href="(.*?)">|)(.*?)(</a>|</dt>)!ims', $this->page['Locations'], $matches) ) {
        for ($i=0;$i<count($matches[0]);++$i)
          $this->locations[] = $matches[0][$i];
      }
    }
    return $this->locations;
  }
```

I like to share this
Greetings
Ed

**Comment by tboothman** [comment]
I think it's time to make the change Ed. Namespaces came to php 6.5 years ago and every version of php that doesn't have them is [out of support](http://php.net/supported-versions.php).
Embrace the change, install composer and come see what it's like with a library that uses an autoloder and actually has some tests.

Slightly more seriously (please upgrade though, it's really only renaming a few classes) I added metacritic ratings a while ago as `Title::metacriticRating()`.
Do you know what the difference between the two recommendations is? If it were to be two methods it would have to be clear what the difference between the two was.
I'm going to have a look at locations, it's down in the far less popular stuff that never got any tests written, and it's not even on the demo page.

**Comment by tboothman** [comment]
Couldn't get the code you posted working, but 4bb84d0 works. I think I'll probably be using DomDocument/DomXPath more, it was easier than the regex I was thinking about

**Comment by duck7000** [comment]
Oke maybe i should upgrade... i thought it would be a lot of work so i postponed it

The difference is that the second method creates a list of recommendations suggested by imdb database.. whatever that means. These are different form the ones on the tilte page
![recommendations](https://cloud.githubusercontent.com/assets/15360048/21909227/4514cab2-d917-11e6-920f-133296930b10.jpg)

**Comment by duck7000** [comment]
Sorry i missed that you already added metacritcs..

The previous version of recommendations that i provided did use xpath but i'm not sure it is faster.
But i find it much more stricter to use

The showphoto is for me very usefull because i can't get the picture to show, proberly due to blocking from imdb

I'm not a professionally skilled programmer.. end still learning

Ed

**Comment by duck7000** [comment]
The method crazy credits doesn.t work properly.
Change the preg_match_all to this
`preg_match_all('!<div class="sodatext">\s*(.*?)\s*</div>!ims',$this->page["CrazyCredits"],$matches)`

Would you like to add the showPhoto method? Maybe it's usefull for others too.
If i use imdbphp the resulting url to the image at imdb doesn't work so i use this to save the photo in a variable only to show that there is picture available. I then use the savephoto method to save

**Comment by tboothman** [comment]
It's an interesting option but downloading an image and injecting it into the html on every page load is far from the standard good way of doing things. You should use `Title::savephoto($path)` to save the image somewhere and serve it from there or `Title::photo_localurl()` which saves the image to `$config->photodir` and gives you a url starting with `$config->photoroot`.
Personally I think the photo_localurl method requires far more figuring out than it saves in convenience.

**Comment by duck7000** [comment]
Oke well i'm just a hobby programmer so please give me a little credit.. i obvious didn't know that.

I did use photo_localurl for that purpose but i end up with a server full of useless pictures that i never use again. That's why i started to use this method, but i understand now that it is bad practice?

**Comment by duck7000** [comment]
I personally think that the soundtrack method is much to complicated.
I use this method , it works well but only the titel is split from the rest that is available, but that is fine by me, maybe not by others though

```
public function soundtrack() {
   if (empty($this->soundtracks)) {
     if (empty($this->page["Soundtrack"])) $this->openpage("Soundtrack");
     if ($this->page["Soundtrack"] == "cannot open page") return array(); // no such page
     if (preg_match_all('!class="soundTrack soda (odd|even)"\s*>\s*(?<title>.+?)<br\s*/>(?<desc>.+?)</div>!ims',str_replace("\n"," ",$this->page["Soundtrack"]),$matches)) {
		$mc = count($matches[0]);
        for ($i=0;$i<$mc;++$i) {
          $s['soundtrack'] = trim($matches['title'][$i]);
		  $s['credits'] = array();
		  $s['credits'][] = array('credit_to'=>str_replace("<br /> ","\n",$matches['desc'][$i]));
          $this->soundtracks[] = $s;
        }
     }
   }
   return $this->soundtracks;
   
  }
```
Maybe you can look in to this?

**Comment by duck7000** [comment]
In the meantime i updated to the latest version of imdbphp!
It wasn't that hard indeed, i had to rewrite one line of my code
The mountain is always bigger than you think..
Thanks!

**Comment by tboothman** [comment]
Edit: This is in response to two comments ago:

Sure, sorry, it's hard to tone this right without sounding condescending or unhelpful because I don't know what you know or what you're using this for.
For a public facing website it'd be fairly bad practice to inject big images into the page that you freshly download from imdb because 1. downloading images on demand is going to make the page load slower than having it ready to go. 2. if you inline the image with data: you make the page larger and on subsequent visits to the page you'd have to download the image again 3. you'd be wasting server bandwidth by having to download and upload the image for the user.
If it's pretty much just for you then yes that'd save you having to store an image that you'd probably never see again.

**Comment by duck7000** [comment]
Oke no offense taken here haha

I'm glad you explained why so now i understand!
I will use photo_localurl again and try to find a way to delete the picture after i'm sure i don't need it anymore

**Comment by tboothman** [comment]
What is it you use this library for, if you don't mind me asking?

**Comment by tboothman** [comment]
I agree with the soundtrack method. I started testing it then gave up, it's a bit of a mess. (I've just written "This function doesn't really work very well" and commented out most of the test...)

One of the big problems I have with this library is it's really hard to judge when to rewrite a method. If someone's using it already then they might not appreciate it being completely redone.
The change I made to `Title:locations()` isn't backwards compatible and if someone's using it (which they're not because only you just noticed it doesn't work) I've got to justify why it's better and make it obvious it's changed.
Given how complicated the soundtracks method is i'd be a little reluctant to just gut it.

**Comment by duck7000** [comment]
I use it in a personal movie database program.
I use it to find the movie information at imdb, save the output to a form at the add page.
On this page i would like to see the image if available. after i save this page to the database the form use the savephoto method to actually save the photo. If i use the url link from the photo method the image is not shown, probably due restrictions from imdb 

It's a fairly old program that i updated to php 7.1 recently (it took me a while because of lack of skills)

**Comment by duck7000** [comment]
Oke i understand

But broken or not usable methods is no good to anyone.
Maybe if you changes things, you can documented it very well what exactly changed.
I think that as long as the output (array) is not changed users would't mind much i guess

I doubt that someone is using the soundtrack method right now, maybe just the title and forget about the rest. In that light seen my method isn't so bad just document the change very well

Did you get very much complaints when you changed all the classnames and removed some old stuff?

**Comment by jreklund** [comment]
@duck7000 Have you tried `photo()` efter upgrading to imdbphp v5+?
After IMDb started to host all images on Amazon instead on their own server, that function started to displays the image for me (on local and webb host). I had the same problem before, that I needed to visit that movie/tv-show IMDb page before I could just echo it out inside an image tag.

**Comment by duck7000** [comment]
@jreklund 
That's something to try!
Thanks!

**Comment by duck7000** [comment]
I tried it and it works!
This used to be a major problem

**Comment by duck7000** [comment]
Thanks for fixing/ adding crazy credits!

Are you considering changing the soundtrack method as well?
I get your concern about drastic changes but i think like it is nobody actually use it

**Comment by tboothman** [comment]
Here's my first attempt ....
9ca2a1d0ced6994b866e6ed776323b88ceed1d38

**Comment by duck7000** [comment]
It looks very promising!

I like that you give a user choices, for me the credits full is what i need/want.
And of course the title
Thanks!

**Comment by duck7000** [comment]
A thought about your attempt for soundtracks

The array credit_to and desc maybe a problem?
Look at the soundtracks info of the following movies:
2001: A Space Odyssey (imdb: 0062622)
A Clockwork Orange (imdb: 0066921)
Those movies have (year) or (uncredited) in the soundtrack sections.

Maybe it's best to let the splitting of anything except the title up te the user?
Or get every line, except the title, in a separate index in a array credit_to or desc and let it up to the user what he/she wants to do with it?

I'm NOT criticize your work, just try to help make it beter, and i'm pretty sure that you have much more knowledge of this as i do..

**Comment by duck7000** [comment]
Just a followup

Are you still working on the soundtrack method?
You didn't implant it in the master so i'm just wondering

Ed

**Comment by tboothman** [comment]
I couldn't decide if it was a good idea or not, I obviously decided at the time from the commit message that removing the stuff that barely worked was fine ... but it did offer a little functionality that I guess is harder now.
