### ISSUE TITLE
What are the current requirements for imdbphp?

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#76]
In the docs it state that you need pear http_request class, is that still the case?

If so there is a newer version of this class HTTP_request2 
Wich one should i use?

**Comment by jreklund** [comment]
No, that changed from v5. You never needed it thought due to the BrowserEmulator class.
This project now depends on cURL instead and you need php > 5.3.

@tboothman composer.json still reference BrowserEmulator and MoviePosterDb.

**Comment by tboothman** [comment]
Sorry ed, I've never actually read any of the stuff in the doc folder so I didn't think to update it.
Would you say the content of the main readme.md is good enough for someone to get started?

**Comment by duck7000** [comment]
Oke so now it uses curl instead of pear http_request, that should have been in the readme

one other point to this.
I don't have a ssl certificate on my apache webserver. If i want to save the imdb cover picture this doesn't work en spits out a error about not finding a certificate. It should mention in the readme that this is a requirement sinds you use curl.
If i comment this out in the photo section and add file_gets_content it works fine

**Comment by tboothman** [comment]
It's likely you're missing a root certificate for amazon's ssl certificate. I'm sure google will provide an answer, but it probably depends on your OS as to what that is.

**Comment by duck7000** [comment]
Oke i try to find it on Google

The problem is due to a missing certificate from amazon? Not because i'm not using a certificate on my server correct?

I use Windows by the way

**Comment by duck7000** [comment]
i searched Google but can't find anything useful because i'm not sure where to look for.
Can you point me in the right direction?

The problem is because my webbrowser has no certificate to verify amazon correct?

This is the error i get:

`Fatal error: Uncaught Imdb\Exception\Http: Failed fetch url [https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_UX182_CR0,0,182,268_AL_.jpg] SSL certificate problem: unable to get local issuer certificate in C:\webserver\wwwroot\phpmoviedb\lib\util\imdbphp\src\Imdb\Request.php:68 Stack trace: #0 C:\webserver\wwwroot\phpmoviedb\lib\util\imdbphp\src\Imdb\Title.php(919): Imdb\Request->sendRequest() #1 C:\webserver\wwwroot\phpmoviedb\includes\movies.inc.php(242): Imdb\Title->savephoto('./movies/729.jp...') #2 C:\webserver\wwwroot\phpmoviedb\index.php(103): require_once('C:\\webserver\\ww...') #3 {main} thrown in C:\webserver\wwwroot\phpmoviedb\lib\util\imdbphp\src\Imdb\Request.php on line 68`

**Comment by jreklund** [comment]
1. Download cacert.pem from here. (rightclick, save link as file)
https://curl.haxx.se/docs/caextract.html
2. Store it somewhere in your computer.
`C:\wamp64\bin\php\php7.0.10\extras\ssl\cacert.pem`
3. Open your php.ini and add the following under [curl]
`curl.cainfo = "C:\wamp64\bin\php\php7.0.10\extras\ssl\cacert.pem"`
4. Restart your server.

**Comment by duck7000** [comment]
@jreklund 
Thanks alot for the info!
When i configured curl i did notice this setting in php.ini but never thought it would need configuration....

It works now!!
Thanks again!

**Comment by jreklund** [comment]
Some food for thoughts regarding the recent readme update. You can only add if after PHP 5.3.7. But who dosen't have that one?!

This will of course work on linux too.
```
/etc/ssl/certs/cacert.pem
curl.cainfo = "/etc/ssl/certs/cacert.pem"
```

But a more recommended way are to update your ca-bundle.crt/ca-certificates.crt file for your whole system. There are different best practices depending on OS. So using Google is your best bet for a safe way.

We can also add this to imdbphp and add a config option to ignore validating SSL aka always working/quick fix, for those who don't have a valid CA Certification.
`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`
Or give people an option to download cacert.pem into /cert/ and activate a _local_ cacert.pem with a configration
`curl_setopt($ch, CURLOPT_CAINFO, "PATH/cert/cacert.pem");`

What are your thoughts about this?

PS. You will need to include some spaces in Gotchas / Help section.

CentOS
---------------
RHEL5
`curl https://curl.haxx.se/ca/cacert.pem --insecure -o /etc/pki/tls/certs/ca-bundle.crt`
or
`wget --no-check-certificate -o /etc/pki/tls/certs/ca-bundle.crt https://curl.haxx.se/ca/cacert.pem`

RHEL 6+
`curl https://curl.haxx.se/ca/cacert.pem --insecure -o /etc/pki/ca-trust/source/anchors/ca-bundle.crt`
or
`wget --no-check-certificate  -o /etc/pki/ca-trust/source/anchors/ca-bundle.crt https://curl.haxx.se/ca/cacert.pem `
And execute:
`update-ca-trust`

**Comment by tboothman** [comment]
I'm not turning off certificate validation, I highly doubt anyone intended that setting to be used for anything other than getting around locally issued certificates.

I didn't make it clear this was just for windows, which curl doesn't seem to have a default behaviour for and requires you to give it a .pem file file. Everyone on a linux style system should be using the cacert that's already in their OS. I've updated the docs.

**Comment by jreklund** [comment]
Fair enough. Anyone that can install a local server will be able to update those settings.

Linux always grabs the built in one; for system updates, curl, wget etc... That's why it's present.
Official PHP binaries for Windows don't include one. WampServer/XAMPP dosen't either. Maybe they all think it will be outdated quickly. Only [curl binaries](https://winampplugins.co.uk/curl/) for Windows include one.
