### ISSUE TITLE
trailers is empty

### ISSUE THREAD

**Issue by kirkdm** [tboothman/imdbphp#77]
when I var_dump($result->trailers(true, true))  or var_dump($result->trailers()) the array is always empty and I'm searching for "The Avengers", on Imdb website they have a trailer for the movie.

**Comment by duck7000** [comment]
As far as i know the trailer class is removed from imdbphp.

There is a thing that is odd though:
In the title.php there is still a method to retrieve trailers?
I'm a little confused

@tboothman Can you clear this up?

**Comment by kirkdm** [comment]
Why remove the trailers that parts is important how can you re-enable this feature

**Comment by tboothman** [comment]
Give that a go now, @kirkdm . I've redone the method, although I don't know which film I can test the second parameter on. Let me know what you find.

**Comment by jreklund** [comment]
That second parameter are never used anymore. They changed that part of imdb in late 2009/2010.
![the lord of the rings the fellowship of the ring 2001 trailers and videos](https://cloud.githubusercontent.com/assets/3641536/22160194/a757bbf2-df44-11e6-835d-8c9ef6a9898f.jpeg)
