### ISSUE TITLE
I can't talk to imdb website anymore 

### ISSUE THREAD

**Issue by kirkdm** [tboothman/imdbphp#78]
I'm getting this error

`Http in Request.php line 68:
Failed fetch url [http://www.imdb.com/offsite/?page-action=offsite-bestmoviesevernews&token=BCYoJJmpHSpsiboKN_9jXtc1h2NS951vIm2UBJuPNLLuEIBRXzR-7xYU9golep91DbdRg7AA_feM%0D%0AzFoxLaE5-UZS7ajMevYdahNLOL7jONBZ0Mtd9FFE_BelaUIiw1l6BwbUgziqfYuYrUQ5fyWTCjU7%0D%0AKiLdGTwqXn-r8C-Y2-yrNC2wi1GtoCw07dmPKj-cwz-lYAKYESb0E2yoBJ0S4IdpU8vuktRgvvT3%0D%0ABIgEUecFFWsybLYWalUgxkDuXdAxhoxg0P5OH8oRDFM0ZGlQqF4Z3w%0D%0A&ref_=ttext_vid_os_0] Failed to connect to www.imdb.com port 80: Host unreachable`

and also this one

`FatalErrorException in Request.php line 149:
Maximum execution time of 60 seconds exceeded`

**Comment by tboothman** [comment]
Your internet or the internet of the computer you're running this on isn't working properly. Can you load imdb.com from it?
