### ISSUE TITLE
imdbphp on windows (localhost)

### ISSUE THREAD

**Issue by Alexisback** [tboothman/imdbphp#79]
and that the correct procedure to install imdbphp on windows in "localhost"?
I installed a web server with apache, php etc., works in localhost
in the file of "imdbphp" and present this "Makefile"
how to install?
There is an installation file to create the database and folders in the right order?

thanks

**Comment by jreklund** [comment]
imdbphp are not a complete application like Wordpress, so there is no database to install.
This is just a library for searching on imdb.com. You can test it out and find example code inside the `demo` folder.
Depending on how you unzipped it:
http://localhost/imdbphp-5.0.3/demo/
http://localhost/demo/

There are however some applications that are using imdbphp to make a complete website, what are you looking for exactly? If you aren't going to make your own.
