### ISSUE TITLE
Missing method Top Rated TV

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#80]
Hi

There is a method for top rated movies but not for top rated tv shows.

Maybe this is something to add to the library?

Maybe you can extend the method top250 to find top rated tv shows as well?

This serie has a top rated value
http://www.imdb.com/title/tt1520211/?ref_=nv_sr_1

Ed

**Comment by duck7000** [comment]
Well nobody seems to have any interest to this, witch is fine by me.

For those who do care, here's my cook up to add this. The output is still the same but can be movie or tv show so in your code you have  to make the difference, perhaps based on the  movie type method?

```
public function top250() {
    if ($this->main_top250 == -1) {
		$this->getPage("Title");
		if (@preg_match('!<a href="[^"]*/chart/top.*>\s*Top Rated Movies #(\d+)\s*</a>!si',$this->page["Title"],$match)) {
			$this->main_top250 = (int)$match[1];
		}
		if (@preg_match('!<a href="[^"]*/chart/top.*>\s*Top Rated TV #(\d+)\s*</a>!si',$this->page["Title"],$match)) {
			$this->main_top250 = (int)$match[1];
		}
		else {
			$this->main_top250 = 0;
		}
    }
    return $this->main_top250;
}
```
Ed

**Comment by duck7000** [comment]
@tboothman 
Any chance that you would implant this in the master?

Ed

**Comment by tboothman** [comment]
Might it be better to separate the top x TV and top x film?

**Comment by tboothman** [comment]
Actually I suppose you can get from the type whether it's TV or film so you'd know if you really cared about the difference between the two

**Comment by duck7000** [comment]
@tboothman 
Yes it is possible to separate tv and movie, but i thought it would be best to combine it?

The thought behind this is that you get the value top 250 regardless of it is movie or tv. The output of the method wouldn't change that way. 
If you think separation is a better option i also agree but in my program i have to create a new database field just for a few tv series,. That's why i extended this method, so i can use the existing top250 database field.

Maybe best of both worlds: capture not only the rating but also the type?
Downside is that the method changes, so users will feel the difference.

I use it like i purposed here and use the movie type method to see the difference, it works well but if you think of a better solution i'm all ears!

Ed

**Comment by duck7000** [comment]
@tboothman 

Thanks for the fix.!
