### ISSUE TITLE
Missing if-statement in function aspect_ratio

### ISSUE THREAD

**Issue by dr-brown** [tboothman/imdbphp#82]
The function _aspect_ratio_ in the title.php (line 399) produces an error if no aspect ratio is given at the corresponding imdb page. Because the _preg_match_ statement in this function has no if clause.

**Comment by tboothman** [comment]
Could you give an example of a film without an aspect ratio please

**Comment by dr-brown** [comment]
http://www.imdb.com/title/tt0105712
