### ISSUE TITLE
imdb closes message board!

### ISSUE THREAD

**Issue by duck7000** [tboothman/imdbphp#84]
Just to inform and maybe interest:

IMPORTANT: IMDb is the world's most popular and authoritative source for movie, TV and celebrity content. As part of our ongoing effort to continually evaluate and enhance the customer experience on IMDb, we have decided to disable IMDb's message boards on February 20, 2017. This includes the Private Message system. After in-depth discussion and examination, we have concluded that IMDb's message boards are no longer providing a positive, useful experience for the vast majority of our more than 250 million monthly users worldwide. The decision to retire a long-standing feature was made only after careful consideration and was based on data and traffic. See more

Is there any interest or way to save the messages from the board?
I know it's tight by time though.

Personally i never used the board but maybe others do

PS If there's no interest,  @tboothman can close this issue

Ed

**Comment by jreklund** [comment]
Personally I never knew it even existed. No use for me.
