### ISSUE TITLE
Movie type also showing other types

### ISSUE THREAD

**Issue by psycholyzern** [tboothman/imdbphp#94]
In demo, when I set type to ```Movie``` it will show result of other types too (eg: episodes, persons, tv series, etc). Same thing happen when I use ```Imdb\TitleSearch::MOVIE```.

**Comment by jreklund** [comment]
What have you been searching for when demo returns `Person` if `Movie` have been selected?
What did you search for when you explicit specify `\Imdb\TitleSearch::MOVIE` as wanted type?

At the moment demo will return the following in `Movie` mode:
```
\Imdb\TitleSearch::MOVIE
\Imdb\TitleSearch::TV_SERIES
\Imdb\TitleSearch::TV_EPISODE
\Imdb\TitleSearch::TV_MINI_SERIES
\Imdb\TitleSearch::TV_MOVIE
\Imdb\TitleSearch::TV_SPECIAL
\Imdb\TitleSearch::TV_SHORT
\Imdb\TitleSearch::GAME
\Imdb\TitleSearch::VIDEO
\Imdb\TitleSearch::SHORT
```
If it can't find anything matching (e.g. documentary) it will return `\Imdb\TitleSearch::MOVIE`.

I haven't found an example where it's returning a person inside `Movie`. It's utilizing `IMDb Category Search` that you will find at their right sidebar.

I have been limiting IMDb too the following:
```php
// Search IMDb for the movie
$imdb = new \Imdb\TitleSearch();
$wantedTypes = array(
	\Imdb\TitleSearch::MOVIE,
	\Imdb\TitleSearch::VIDEO,
	\Imdb\TitleSearch::TV_MOVIE,
	\Imdb\TitleSearch::TV_SERIES,
	\Imdb\TitleSearch::TV_MINI_SERIES
);
$imdbresults = $imdb->search($imdbsearch,$wantedTypes);

// Select Movie/TV Series based on movietypes
$movietypes = array(
	\Imdb\TitleSearch::MOVIE,
	\Imdb\TitleSearch::VIDEO,
	\Imdb\TitleSearch::TV_MOVIE
);
```
And using $movietypes to filter through TV/Movie when looping based on the results.
