### ISSUE TITLE
top250

### ISSUE THREAD

**Issue by parham-box** [tboothman/imdbphp#95]
i was wondering if there is a way to get top250 movies or series chart with their number and imdb id

**Comment by tboothman** [comment]
I don't think so. You can get a title's ranking in the top 250 though.
If you modified TitleSearchAdvanced to be able to accept a group and a search limit you could do it:

http://www.imdb.com/search/title?count=250&groups=top_250

**Comment by parham-box** [comment]
thanks i did it and it works perfectly
