### ISSUE TITLE
SSL Certificate error for akas.imdb.com 

### ISSUE THREAD

**Issue by cyberindy** [tboothman/imdbphp#97]
Imdb\Exception\Http: Failed fetch url [https://akas.imdb.com/title/tt3130560/plotsummary?#synopsis] SSL: no alternative certificate subject name matches target host name 'akas.imdb.com' in /var/www/api/vendor/imdbphp/imdbphp/src/Imdb/Request.php on line 82

Request.php trips over faulty ssl cert for akas.imdb.com

**Comment by cyberindy** [comment]
Setting the curl option CURLOPT_SSL_VERIFYPEER to FALSE might probably solve the issue. 

Unfortunately I'm currently not set up to submit a pull request for this.

**Comment by jreklund** [comment]
Hi, please see the readme regarding "SSL certificate problem: unable to get local issuer certificate".

**Comment by cyberindy** [comment]
Excellent. Thanks a lot for the quick response.
I think similar cases could be avoided though with the CURLOPT_SSL_VERIFYPEER option. The akas domain is still available, only the certificate was exchanged. I can't think for a reason, why imdbphp would need to do ssl verifaction anyway and it could slightly speed up the requests if we just skip it?

**Comment by tboothman** [comment]
Interestingly if you go to akas.imdb.com/title/tt3130560/synopsis you end up on https://akas.imdb.com/title/tt3130560/plotsummary#synopsis
However if you go to www.imdb.com/title/tt3130560/synopsis you end up on http://www.imdb.com/title/tt3130560/plotsummary#synopsis (no SSL)
Also if you try and go to https://www.imdb.com/title/tt3130560/plotsummary#synopsis you get redirected off of SSL
I've changed the url for synopsis so it doesn't need to follow a redirect and @jreklund has given you the solution to your problem.

Ignoring SSL errors is pretty bad practice, and in this instance doing the verification showed up a configuration error.
